### ISSUE TITLE
Summoning (New Enchantment Idea Sword)

### ISSUE THREAD

**Issue by SonOfDeath** [drewhoener/JWSuggestions#10]
Wouldn't be cool to use your sword to summon the undead? 

I'm not sure if this is even possible but how this would work is right clicking with the enchanted item and a zombie/skeleton will appear and will fight with you. This creature is stronger than a regular skeleton/zombie)

Rules (Because it can't be too OP)
Can only have one summoned at one time.
Cooldown 60Sec (So you cannot spam) 
Reduces Durability of the sword faster (Like spawner pick up)
1/100 chance to enchant :)

Of course I don't know what the limitations of minecraft, so what I'm proposing may be impossible.

**Comment by drewhoener** [comment]
I like the idea, I'd like some other opinions though. See if some other people like the idea and send me a screenshot

**Comment by SonOfDeath** [comment]
![2015-03-12_12 14 19](https://cloud.githubusercontent.com/assets/11358583/6626240/6e57a696-c8b2-11e4-9d34-892b58c12ea0.png)

![2015-03-12_12 15 41](https://cloud.githubusercontent.com/assets/11358583/6626274/afc65550-c8b2-11e4-90a6-1bfcbd62f69a.png)

Ill ask when more people get on ;)

**Comment by Duraninator205** [comment]
i would like that but what are the benifits of mobs following you?

**Comment by SonOfDeath** [comment]
No you spawn them and they beat up hostile mobs

**Comment by drewhoener** [comment]
Hmm, I'm trying to figure out if it's possible to change the thing that a zombie targets...

**Comment by SonOfDeath** [comment]
Perhaps we are thinking in the wrong direction.

Why not make it spawn an iron golem?

**Comment by drewhoener** [comment]
Might work. I'd have to configure it to make sure they don't drop items or xp when they die though

**Comment by SonOfDeath** [comment]
True :)

**Comment by OoveVolcae** [comment]
What about smaller, more pesky mobs like endermites or silverfish? Silverfish, with their tendency to burrow, probably wouldn't work. Though, I do have a question, do they just build up and turn into an army that a player has amassed, or do they time out and either die or disappear?

**Comment by drewhoener** [comment]
Just restating, it's hard to <b>make</b> a mob attack something other than what its target is, especially if it's not a player. The most I can do is make them move places to prevent them from attacking the player. Iron golem seems most viable because I can make them follow the player, and they <b>will</b> attack other mobs for the player.

**Comment by littletntman** [comment]
I like the idea but what's the name?

**Comment by stefan3140** [comment]
Why dont u just use a dog, it automaticly attacks hostile mobs?

**Comment by 5d100** [comment]
I like this. it may be like a 5 coin cost or something though.

**Comment by drewhoener** [comment]
I've actually added this a while ago, but it requires tokens to purchase. It's in the buytemp menu. Took a lot of ai tweaking to do, had to make a couple traits from scratch

**Comment by 5d100** [comment]
just saying, shouldn't this be closed?
