### ISSUE TITLE
Staff Age Requirement

### ISSUE THREAD

**Issue by MurdaInc** [drewhoener/JWSuggestions#101]
Murda_Inc

I think the minimum age for staff should be set to 18, my reasoning behind this is that people of a young age tend not to think very clearly or make rational decisions based on fact without bias.

**Comment by drewhoener** [comment]
Huh, interesting idea. So what does that say about me? I'm 17

**Comment by TemperrroniPizza** [comment]
O.O

**Comment by TemperrroniPizza** [comment]
More like 15 and up, I'm 16, so this would be a better idea.

**Comment by johnnywoof** [comment]
The age minimum requirement is there in order to comply with the terms of service with third party tools used.

Why change the age? Because we assume by age 18 the person will be mature. If we find someone younger but still achieves the same maturity, we'll allow them anyways.
