### ISSUE TITLE
death chests

### ISSUE THREAD

**Issue by beardobob** [drewhoener/JWSuggestions#103]
the problem I found is I was in my house someone asked to tpa to me so being nice I ok'd it, I was typing and got killed by zombie I used the /back immediately and came back just in time for them to run over and loot my chest with me standing on it, they took my vorpal sword  which took me a while to make. so to give honest people a chance to get there stuff before the shady vultures pick threw everything. Is it possible to make death chests locked or at least maybe for 10 min then unlock 5 before the 15 min timer runs out,

**Comment by beardobob** [comment]
also with storage chests maybe bump up stacks of items from 64 to 100 or 128

**Comment by drewhoener** [comment]
@beardobob I'm not sure how much you know about the minecraft item system, but the stack size thing isn't really doable at all without specifically recoding all of the item types on the server

**Comment by johnnywoof** [comment]
Death chests were primarily added to preserve the life time of dropped items.
Because anyone can pick up dropped items, death chests mimic the same idea by being unlocked.
