### ISSUE TITLE
Trivias

### ISSUE THREAD

**Issue by PandaChristinaTFR** [drewhoener/JWSuggestions#104]
PandaChristina

I love participating in the server Trivia's that the staff like to throw out, but could there be a specific chat command, or maybe even a little area for /l use for people who would like participate, because the spam in chat almost always causes me a lot of lag and crashing, so if possible I'd extremely appreciate some sort of separate system for these. 

Thank ya. <3

**Comment by drewhoener** [comment]
I'm reworking chat. It's been in the works for a while and I think you'll enjoy it xD

**Comment by PandaChristinaTFR** [comment]
Yay! Thank you! <3
