### ISSUE TITLE
/sellhead

### ISSUE THREAD

**Issue by KrazyKid27** [drewhoener/JWSuggestions#105]
I feel like /sellhead would be the ideal inverse of /buyhead for the accidental purchases or rewards of unwanted heads. 

Mechanics are simple, similar to those of /sponge.
Just like how it is easy to purchase a sponge by specifying the size, the /buyhead command is easy by just specifying the player name. However, there may come the mishap of a possible misspelling of the name of the player or confusion for another reason. By implementing /sellhead there are no worries of these possibilities leaving you stuck with a head that you have nearly no use for. Following the purchase of an unwanted head you can simply type /sellhead and deposit the head(s) into the available space (the same as the /sponge sell system, only with the use of heads). Following this the player will be reimbursed with the 5,000, 10,000, or 20,000 (in the case of Big J's head :D) that they spent on the head.

I hope you will take this new system into consideration and I hope to possibly see it implemented in the future! :D 
                                                                                                                                      -Krazy.

**Comment by johnnywoof** [comment]
There are a lot of player heads that were obtained in various ways besides via /buyhead
(e.g. Hoog's birthday)

I'm afraid adding a command like this late-game will cause some balances to inflate.
