### ISSUE TITLE
Awesome Suggestion!

### ISSUE THREAD

**Issue by PancakezJW** [drewhoener/JWSuggestions#108]
I really want to be able to take my friends horse out for her daily walk cause my friend is on vacation. I cant though. I was wondering if you could be able to allow certain people to ride your horses! <3 Thanks!

**Comment by TemperrroniPizza** [comment]
Like you have access to it, via feeding and primary care, while others can ride it, that you allow access to. I think there is a point where this goes too far. Wanting to give a daily ride for a horse in Minecraft, if this is more of a novelty item. Not a real purposeful thing to be added to the server. I'm not hating, I'm giving my honest opinion to, in my opinion, an appropriate idea for you and a couple of other people, but not for the rest of the server. This repository is guided towards a larger set of ideas, that could help the server greatly. Even little things like chat filters, and extra "needed" options to wp flags, that will help us substantially.
