### ISSUE TITLE
Local Chat

### ISSUE THREAD

**Issue by Duraninator205** [drewhoener/JWSuggestions#11]
Local chat should have color chat just like main chat and Donator because this would make certian things WAY more easier one of the reason i want this is because /l is underused

RULES:
No spamming of color
No spamming &K
Things Added (if added)
Color chat in /l or /local 
Server benifits:
More donations to Uliment+
/l used more

And thats my suggestion please comment down below!

**Comment by johnnywoof** [comment]
Basically color support for local chat?

**Comment by drewhoener** [comment]
yeah, I think that's it

**Comment by Duraninator205** [comment]
Yeah color support for /l

**Comment by Duraninator205** [comment]
How did i close it?

**Comment by Duraninator205** [comment]
Nvm

**Comment by Duraninator205** [comment]
Yay thanks johnny

**Comment by Duraninator205** [comment]
You may now close. Thanks for Answering

**Comment by johnnywoof** [comment]
Deployed.
