### ISSUE TITLE
Wp flags Teleportation

### ISSUE THREAD

**Issue by Abbiyoyo** [drewhoener/JWSuggestions#110]
On /wp flags Teleportation disables and ables both /tpa and enderpearls. How about add an option for both? Because in a lot of my protected areas I would like to able tpas but disable enderpearls!

**Comment by 5d100** [comment]
this is big, because you should be able to go into an area, but say that you have a mob spawner, you don't want people to teleport into it, and so differentiating between them would be pretty big.

**Comment by johnnywoof** [comment]
Implemented.
