### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by IsabelleCajan** [drewhoener/JWSuggestions#112]
IsabelleCajan~
There should be a rank for the older players of the server. Like the players that have been on for a long time. It doesnt give you any perks but it changes your rank to [Oldie]<username>. And players who are noobs know that someone with that rank can help out with rules and such.

**Comment by drewhoener** [comment]
Nope. The oldie group was ruined. [Hint hint]

**Comment by 5d100** [comment]
it could be started anew when the new server comes out, or when this is implemented. that's an idea for this

**Comment by drewhoener** [comment]
No

**Comment by drewhoener** [comment]
If you want, I'm sure isabelle would be happy to explain why I think so little of her 'oldies' idea now.
