### ISSUE TITLE
dragons in build world

### ISSUE THREAD

**Issue by beardobob** [drewhoener/JWSuggestions#114]
can you add dragons to build world, and maybe have eggs from them (like wolves) that maybe can protect homes,  possibly have bad dragons red/fire, blue/ligntning, or green/poison.  and egg drops from them (like gold vegies) put gold or iron bars/nuggets around them to make gold or iron good dragon eggs that spawn pets

**Comment by johnnywoof** [comment]
The amount of effort required for the gain is too high.
It's going to be difficult, near impossible, to add dragons in the build world.
