### ISSUE TITLE
Clear Lag

### ISSUE THREAD

**Issue by PancakezOnMC** [drewhoener/JWSuggestions#117]
It'd be a great idea to have something called "Clear Lag" What it would do is you know when so many people have left so many items dropped in the worlds it causes intense lag? Well Clear lag publically would tell you every 15 - 30 minutes "Clear Lag" Would happen and it would take 5 or so seconds (idk) to sweep up every item that has been left on the ground and tell the players something like this "Clear Lag Complete Picked up 1743 items" Cause the more and more items that lay down causes lag for me and my friends and we created an idea for this! We really hope you take this idea and mess around with it. Got any questions about the idea ask down below. Might not reply too soon cause my emails are SLOW! Thanks! -Pancakez

**Comment by 5d100** [comment]
this is great in theory, but the problem I've experienced, is when I was mining, it took me about 15 minutes to find a diamond, but when I mined it, it disappeared due to clear lag. so, you might want to do this everywhere except mine world.

**Comment by PancakezOnMC** [comment]
Yeah. Remove it from mineworld maybe or for mineworld have it set for 1 hour or so? Good suggestion. Thanks 5d100!

**Comment by drewhoener** [comment]
Also, this isn't really a viable solution to lag. most of ours comes from a large amount of entities and tile data. not items...
