### ISSUE TITLE
lava boat?

### ISSUE THREAD

**Issue by 5d100** [drewhoener/JWSuggestions#118]
so, donators have flying enabled, but for vanilla players, I think that we should have a boat that can be used in lava. It would have the same recipe as a boat, but you would use iron blocks instead of wood, as that would make it so not everyone would be making the boats. also, it would add something to give the coins more value possibly.

**Comment by johnnywoof** [comment]
Not sure why this needs to be added, but why not.

**Comment by 5d100** [comment]
it's for the non-donators if they want to travel across lava, and if you want to make a nether fortress out of quartz, you may want it for cosmetic reasons.

**Comment by 5d100** [comment]
or quartz. quartz would be a good ingredient. whether it be the blocks or it be the ore.

**Comment by johnnywoof** [comment]
Unfortunately it isn't easy to implement a lava boat into the survival server.
