### ISSUE TITLE
/cmodify fix

### ISSUE THREAD

**Issue by 5d100** [drewhoener/JWSuggestions#119]
so, it's kinda annoying to go and add a single person to every chest in an area (say a sponge) and so you should be able to do something like,

/cmodify Dave_Darkriser sponge

to add someone to all locked objects in a sponge.

**Comment by drewhoener** [comment]
That's actually possible, but imo it would require way more resources than I'm willing to dedicate to the one simple thing. It involves looking over every single tile entity in the chunk and checking if they're locked by the sponge owner. Relatively simple, but think if you're in something like a guardian farm... Hundreds of hoppers and the server has to spend valuable time and ticks checking each of them. Not to mention signs and furnaces, etc. Checking every single one causes lag, the thing that you guys always complain about (even if it isn't really there xD). So long story short, I can't afford to dedicate the server time to doing it at this time, maybe in the future
