### ISSUE TITLE
Messaging

### ISSUE THREAD

**Issue by Duraninator205** [drewhoener/JWSuggestions#12]
Msgs should have Colorchat!
This will make more donations to Ultimint which will make the server better!

This is colored msg support

**Comment by SonOfDeath** [comment]
Im going with a no with this one, yes it would be cool I guess.

But I don't see a use for it.

**Comment by Duraninator205** [comment]
Its like /a or /l
or main chat

**Comment by SonOfDeath** [comment]
I kinda like the messages they way they are tho...

**Comment by johnnywoof** [comment]
No need for this.

**Comment by Duraninator205** [comment]
.....
