### ISSUE TITLE
delete bucket

### ISSUE THREAD

**Issue by 5d100** [drewhoener/JWSuggestions#120]
so, I say that the donators should get a perk where we have a bucket, it stays empty, and whenever you put something in it, (lava or water) it disappears, thus making the draining of a lava cavern so much easier. think that would be possible?

this could be anywhere from a lord donator to platinum. just an idea.

**Comment by johnnywoof** [comment]
Unfortunately this item will be abused.
Players will drain huge sections of the world with the delete bucket.
