### ISSUE TITLE
Freezing the bank

### ISSUE THREAD

**Issue by PancakezOnMC** [drewhoener/JWSuggestions#121]
*cough cough* A lot of players have been complaining about spending their money too much. Pandi and I have come up with a solution! Having a command called /BankFreeze or /Bfreeze! What you do for the command could be something like /BankFreeze [time you want it to be frozen for] Now I have already understood some people could freeze their bank for too long. You would have to insert 00:00:00 Going from hour, to minute, to second. So say I really needed to freeze up 15k in the bank for 20 minutes and 30 seconds. I would do /bankfreeze 00:20:30 and that could freeze up my bank account so I could not pull money out. It's a great way to teach younger when to and when not to freeze your bank. I do understand sometimes people might need the money when they freeze their bank. That's their choice. They have to be responsible about their money. When they run out while it is frozen, they run out. 

Additional: I know you might not add this addition but sometimes for punishment a mod or something could freeze their account for however long they need it to be froze. I don't know. My friend told me to say this.

**Comment by PandaChristina** [comment]
Aha, I admit to helping out with the general form of this idea. I thought it would be cool if you could find a way to freeze your coins (for those like me who cannot have untouched coins ever) so you have to suck it up and find a different way to buy whatever it was you wanted. If this could be added in to the bank system, that would be pretty cool! :3

**Comment by PancakezOnMC** [comment]
Mhm. Go Pandi for bringing up the idea! *claps*

**Comment by rockerjman222** [comment]
There would be no real gain to this.
