### ISSUE TITLE
/donate

### ISSUE THREAD

**Issue by PancakezOnMC** [drewhoener/JWSuggestions#122]
I figured when donating some lords cannot donate anymore. And they really want to. Well we should be able to buy coins from /donate I don't know reasonable prices but something like $1 USD for 1k coins. The price is up to you. I just thought it would help the server and the Lord's (and other people) anxious to donate. Just popped into my mind. Add on if you want. Also we should be able to freely donate any money with no perk cause some people do that. Just look closer into this idea. Thanks you. 0w0

**Comment by drewhoener** [comment]
Nope. Mojang has specifically said that servers can't sell in game currency for real money

**Comment by PancakezOnMC** [comment]
oh POOP YOU MOJANG
