### ISSUE TITLE
Plugin Mcmmo

### ISSUE THREAD

**Issue by Bossmob75** [drewhoener/JWSuggestions#125]
This is a basic plugin for many servers it adds the ability to gain levels (not xp) for mining and fighting mobs and many other minecraft attributes it adds more reason to play and more fun

**Comment by drewhoener** [comment]
The thing is though, we're a pve based server, not an mmo based one

**Comment by Bossmob75** [comment]
it dosent make it mmo its just a name its a helpful idea and add fun

**Comment by Bossmob75** [comment]
faction servers other towny servers just little  to add to help spice up the adventure

**Comment by drewhoener** [comment]
yeah, I've considered making a faction or mcmmo plugin for a different server
