### ISSUE TITLE
Mcmmo

### ISSUE THREAD

**Issue by Bossmob75** [drewhoener/JWSuggestions#126]
this is a great plugin used for many servers in minecraft factions prison towny and more so it would be a good idea to add it now and add more fun into the game

**Comment by Bossmob75** [comment]
sorry if there is 2i closed the last one

**Comment by Bossmob75** [comment]
srry for my bad grammar

**Comment by OoveVolcae** [comment]
We currently have a town system up and running. Players can join other player-made towns to get some cool town-made perks! The prison game mode has been suggested before. While I don't see much value in it, the interest it has received might make it something to consider when JW expands to get new servers.

**Comment by Bossmob75** [comment]
what I mean by that is mcmmo are on those types of servers

**Comment by drewhoener** [comment]
just curious why you closed the one I commented on xD oove kind of restated what I told you

**Comment by Bossmob75** [comment]
I did that on axxedent im new to git hub

**Comment by Bossmob75** [comment]
again a suck at grammar
