### ISSUE TITLE
In-game weather issue and solution [/weather default]

### ISSUE THREAD

**Issue by Zefferis** [drewhoener/JWSuggestions#127]
Hello!

I had a conversation with Admin Harmony about this earlier and decided to do some testing to see what the server was doing! Alas these are my summaries:

1. The Server has its own weather patterns which effect game-play and players should be aware of weather conditions to alter their play in accordance with the weather.

2. If a player uses the [/weather on|off] command then their local experience of weather is permanently altered to either show weather effect or not to show weather effects.

3. This is a benefit for players who may experience lag / or would wish to not see the aesthetics of weather locally however alters game-play unfavorably if that same player is not able to check real weather conditions.

4. There is no current method of checking or reverting back to real weather conditions for player who have used the /weather command a total of one or more times

With those I would ask that a new command be added: [/weather default] so that the options are [/weather on|off|default]

[/weather on] currently permanently causes aesthetic weather effects to occur that do not effect actual in-game mechanics until turned "off"; which is fine for aesthetic reasons.

[/weather off] currently permanently causes all weather animation effects for the region the player is in to not occur, even if there is a weather effect in place in-game changing game mechanics.

[/weather default] in this case should remove the effects of either [/weather on|off] so that the player will again experience the weather effects that are occurring in-game that would change the then present game-mechanics ((such as snow layering, early mob spawning during a storm, fishing, ect.)).

Thank you!! I'm just a little disappointed that now that I've used the weather command once I can no longer keep track of when it's raining, stormy or snowing :(

**Comment by TemperrroniPizza** [comment]
The server has the plugin /weather. You can do /weather on, to turn on continuous rain and snow, or do /weather off, to turn off the weather permanently. This was implemented because a majority of us do not want default weather because we find it annoying. I keep my weather on permanently because I use custom made shaders, and I like my rainy effects, rain reflections, small puddles with adaptation to Parallax occlusion mapping (POM), etc. /also, some players do not have very powerful PC's, which does lead to some lag and poor performance if not turned off. If we did this we will all lose some performance. Heck! People will start leaving if this wasn't implemented.

**Comment by drewhoener** [comment]
actually it's not a plugin, it's just a custom command I coded

**Comment by TemperrroniPizza** [comment]
Drew, such a card XDDDD

**Comment by TemperrroniPizza** [comment]
But would you find it annoying if you had to deal with default weather? I think this is a fantastic idea!!! I wish this could be implemented into a wp flag, where you can change the weather into  snow particles, fire storm, arrow storm, and the other types.

**Comment by TemperrroniPizza** [comment]
basically using particle packs with weather if you are a pro donator or higher, would be neat :D

**Comment by TemperrroniPizza** [comment]
XD

**Comment by 5d100** [comment]
i'm supportive of that. particle effects would be cool.

**Comment by Zefferis** [comment]
"This was implemented because a majority of us do not want default weather because we find it annoying"

^ That's totally understandable; and MissLovedChi, the player I play with doesn't like the snow/rain either because of the lag it causes her.

The issue though is that since its a permanent change to what you as the player see and doesn't actually change whats happening in the server - things like fishing have mechanics tied to rain which makes catching items and fishing go much quicker; I think it would be beneficial to somehow identify when it was actually raining to know when I should go fishing.

Because right now since I've used the command I've lost that ability which I wasn't aware I was going to lose - If I knew it was going to have this kind of lasting effect I personally wouldn't have used the command; and there's no command to revert back to just seeing what the actual weather is like.

**Comment by Zefferis** [comment]
Hey, just wanted to write a response to remind folks about the suggestion (:

Again, the suggestion wasn't about the effects of particles, that's subsidiary to the knowledge of weather conditions in-game that effect in-game mechanics such as snowfall (snow layer production), thunder (skeleton horses, witches, charged creepers), and fishing (decreased lure time).

The command currently permanently alters in-game experience with understanding weather conditions since its completely overridden by a cosmetic change; having the ability to revert your own view of weather particles or a command to check local weather conditions would eliminate the issue in question.

Again the issue mainly came out of not knowing when it was snowing in-game and when it was raining for best fishing conditions.

Thanks ~~

**Comment by johnnywoof** [comment]
Suggestion has been coded and will be released upon the next update of survival.

**Comment by johnnywoof** [comment]
Deployed.
