### ISSUE TITLE
Horse Eggs Not Showing Speed

### ISSUE THREAD

**Issue by DoctorHax** [drewhoener/JWSuggestions#128]
DoctorHax

Heya, I was just wondering if in the future horse eggs could show the horse's speed.  It currently shows the jump height, but the speed for it is nonexistent.  This would be really cool and help you easily find which one of your horses is fastest.

**Comment by 5d100** [comment]
I thought it reset every time you captured it.

**Comment by DoctorHax** [comment]
After testing, I have come to the conclusion that horse speed does in fact reset.  Oh well.

**Comment by drewhoener** [comment]
looked through the code, as far as I can tell, speed isn't actually something I can access through the code....
