### ISSUE TITLE
Repairing Items

### ISSUE THREAD

**Issue by GSOslayer01** [drewhoener/JWSuggestions#132]
hey its GSOslayer01, 
 I was wondering if you could add where Epic+ could have the option to do /repair or /fix to repair the object they are holding

**Comment by SonOfDeath** [comment]
Yeah no, it has been brought up before.. You see /fix is waaaay too op especially with spawnerpickup pics or onehit swords

**Comment by GSOslayer01** [comment]
@SonOfDeath maybe u can code it where some items cant be fixed

**Comment by johnnywoof** [comment]
This idea been suggested many times. We have no plans of adding it.
