### ISSUE TITLE
EnderMine (rare enchant on any tool besides hoe)

### ISSUE THREAD

**Issue by RebeccaAMGG** [drewhoener/JWSuggestions#133]
An enchantment that anytime u mine something, it goes to your inventory instead of dropping to the ground, unless your inventory is full. if its full then there can be a message saying 'your inventory is too full!' or it can drop on the ground :3

**Comment by drewhoener** [comment]
ooh I like this one

**Comment by BlueKnightSam** [comment]
Reminds me of the Ender Collector @drewhoener

**Comment by PianoPlayingHusky** [comment]
I saw these on other servers too and it's really efficient like if you're strip mining or somethin

**Comment by drewhoener** [comment]
Done, it was a pain in the ass to write but I had fun...needs a lot of testing

**Comment by 5d100** [comment]
i'm open for testing if needed.

**Comment by drewhoener** [comment]
spent a lot of time testing it, I'm incredibly confident it works

**Comment by johnnywoof** [comment]
Already deployed on the server as suction enchantment

**Comment by RebeccaAMGG** [comment]
ouo omg you guuuys I cant believe it actually happened xD

**Comment by drewhoener** [comment]
it took me a crazy long time to actually figure out, but it's been on there a while
