### ISSUE TITLE
Chopping Trees Faster

### ISSUE THREAD

**Issue by GSOslayer01** [drewhoener/JWSuggestions#134]
Hey i think their should be a coding for Epic+. My idea is including Epics bc Lords have 2 wands already so we should include them with something eles. There should be an axe that destroys the whole tree with only destroying the bottum block

**Comment by drewhoener** [comment]
I've considered it, but it's hard to accomplish, simply becuase it could destroy entire houses with a single swing. Also, saying that epic should have a feature becuase lords got features isn't exactly correct, lords didn't have enough for the amount of money that they give, so I evened the playing field

**Comment by drewhoener** [comment]
- [ ]

**Comment by 5d100** [comment]
this would work better if it was only the full tree blocks and not the wooden planks.

**Comment by drewhoener** [comment]
lots and lots of people implement the wood blocks into their builds, hence my hesitation
also, I think GSO is missing the point that just becuase I gave a wand to Epic, I <b>HAVE</b> to give one to the epic donators; I absolutely don't. I didn't feel like Lord donators had enough incentive to donate for the extra $50 that they're giving to the server, so I made them some fun things

**Comment by johnnywoof** [comment]
This idea been suggested several times. Unfortunately, there isn't any fool-proof algorithm that can be designed to only cut down trees.
