### ISSUE TITLE
Shulker disguise

### ISSUE THREAD

**Issue by PianoPlayingHusky** [drewhoener/JWSuggestions#138]
Just another disguise in /d, it'd be cool if we could disguise as shulkers and still move around but looking like a block/

**Comment by TemperrroniPizza** [comment]
That seems like a possibility, but the mechanics or the shulker will make it difficult to make, unless you could vanish a minecart and have it follow you on a delay like the morphs they have on hypixel.

**Comment by BlueKnightSam** [comment]
We will look into getting this... there seems to be some issues with 1.9 in disguises that we are working to fix.

**Comment by johnnywoof** [comment]
Implemented, but may not be available. We've discovered that shulkers do not move like normal mobs.
