### ISSUE TITLE
/beaconrange

### ISSUE THREAD

**Issue by 2scoopsrice** [drewhoener/JWSuggestions#140]
Just a simple command that would be nice to see what the range of your beacon is. Like viewregions, but with beacons.

**Comment by 5d100** [comment]
this would be nice, I agree with this one.

**Comment by drewhoener** [comment]
I'm actually not sure if I can do this, I'll look into it

**Comment by johnnywoof** [comment]
Unfortunately, it isn't possible to modify the beacon range.
