### ISSUE TITLE
Craftable Elytra  

### ISSUE THREAD

**Issue by Ducky22** [drewhoener/JWSuggestions#144]
there hard to get to when you cant fly and they cost a lot for players who dont have a lot to spend. elytra are awesome and people enjoy this new feature what would make this new feature better? mini games ect. -Danny_Ducky22 *also know as monsterdan22*

**Comment by johnnywoof** [comment]
What is your suggestion for the crafting recipe?

**Comment by drewhoener** [comment]
Just want to put it on record, there are infinite elytra on our server, since we have an end mineworld that resets every week and there's multiple dungeons each with an elytra

**Comment by Ducky22** [comment]
Johnnywoof i was thinking maybe something like this 
![2016-03-24_15 14 22](https://cloud.githubusercontent.com/assets/17996980/14030009/638ae552-f1d3-11e5-8695-90b4387daabb.png)

**Comment by Ducky22** [comment]
Or maybe something like this even
![2016-03-24_15 21 01](https://cloud.githubusercontent.com/assets/17996980/14030146/1f554ebc-f1d4-11e5-9ed4-c036933d8a6c.png)

**Comment by Ducky22** [comment]
May i also include I have had an intense and boring experience looking for elytra it isnt fun to look for them and when you finally find and end ship its already looted its an extremely painful process ;-;

**Comment by 5d100** [comment]
the diamond armor one seems like it would be a nice touch. I second this one.

**Comment by drewhoener** [comment]
@Ducky22 I've also had a lot of experience looking for elytra and having no effort. If the item weren't rare, then there would be no incentive to obtain it, adding the recipe removes all the incentive for people to go looking for them.
Unfortunately I don't think I can add this one at this point, though I will consider it for the future: they're just too rare and important to add a simple recipe for
