### ISSUE TITLE
A new way to stack items /stack

### ISSUE THREAD

**Issue by CakePrincess** [drewhoener/JWSuggestions#145]
**IGN**CakePrincess
**Request/Reason** /Stack, an easy way for players and donators to stack items for easy storage or use for shops. For example, you're selling cake at your shop or carrying cake, and since cake doesn't stack you could hold the cake in your hand and do /stack and it automatically puts the cake in a stack. A max of (64 per stack on each item). Another example would be boats. Thanks for taking your time to look at my idea <3
~CakePrincess

**Comment by drewhoener** [comment]
well, considering that I aim to keep most minecraft mechanics unchanged, I dont' think I can implement this. Cakes were never meant to stack above 1, like eggs were never meant to stack above 16. I could definitely do it, but then we'll have people stacking items when they weren't meant to be stacked in the first place
