### ISSUE TITLE
a bank account for 2 people

### ISSUE THREAD

**Issue by WolfyCraft** [drewhoener/JWSuggestions#146]
hi i'm WolfyCraft i played on the server alot it's a great server but i always play with my friend we have a town together and a shop so i woud really like a bank account for 2 (or more) people so we coud share our money it woud make it alot more easy to play together

**Comment by Zefferis** [comment]
Personally like the idea, I play with MissLovedChi and it's pretty much just me and her so all of our items are shared including what we spend our coins on; a joint-bank separate from the personal balance would be nifty

Like an extension to /bank?


/jbank create <bankname>
/jbank delete <bankname>
>/jbank yes

/jbank accept <playername>
/jbank decline <playername>

/jbank join <bankname>

/jbank enter <bal>
/jbank withdraw <bal>

/jbank info
> Bank Name, Bank Admin, Balance, Players in Joint-Bank


Eh, there's a lot of fundamental issues regarding the deletion of a joint bank perhaps? But I like the idea of a joint bank for myself and MissLovedChi

**Comment by PianoPlayingHusky** [comment]
Would it be possible for the other person to steal? There could be a "history" to the bank so it's like when you do /jbank history, you see how much a person deposited/withdrew. That way if someone thinks their bank partner took more than their share, they will have proof.

**Comment by drewhoener** [comment]
@PianoPlayingHusky @Zefferis
It's not a bad idea but I think at this point since our player-base is so small, it's not quite worth implementing now. In the future it would be good to have, we can revisit the issue after 4.0 is released and we've put more money towards advertising

**Comment by johnnywoof** [comment]
Implemented in 4.0
Check /bank help
