### ISSUE TITLE
Issue with QuickStrike in 1.9

### ISSUE THREAD

**Issue by Zefferis** [drewhoener/JWSuggestions#147]
Hey folks,

Just wanted to report something I found recently with my newly aquired quickstrike diamond sword.

Ended up putting Sharpness V on it and when I went to test it out I found that the sharpness didn't seem to take effect, infact the entire weapon didn't have a attack damage indicator, it stated the item was at +1024 Attack Speed, but no damage.

So it seems the weapon is really quick but deals less damage than an enchanted iron sword.

Unsure if that is intended, if it isn't then there ya go ~ A suggestion (:

Thanks,
Z

**Comment by drewhoener** [comment]
Interesting, I'm completely overwriting it...
I'll get right on that

**Comment by drewhoener** [comment]
@Zefferis just to confirm, The numbers you're expecting are the ones from 1.9 with reduced damage from sharpness?

**Comment by TemperrroniPizza** [comment]
This is something I had encountered too, thanks for pointing it out in more detail Zeff

**Comment by drewhoener** [comment]
Just tested, even if you might not be able to see exactly how much damage it does, I can assure you that the effect given by sharpness still takes effect. 1.9 really changed combat, so a lot of stuff does a lot less damage than before. Took about 21 strikes to kill a zombie normally, 15 with the sharpness or something like that
