### ISSUE TITLE
Ability to loot chests in BuildWorld (possible conditions)

### ISSUE THREAD

**Issue by Zefferis** [drewhoener/JWSuggestions#148]
Her, curiously there are certain players who've been offline for so long that their land is no longer claimed, yet their items in locked chests in particular remain locked and immovable.

MissLovedChi and I thought locked chests could be tied to log-duration, so after 2 months of inactivity the lock would go away, or that locked items can only be locked when inside a sponged region so that way random lockable items in the world can be removed or altered when there is no clear owner of property, or a lack of owner.

Thanks (:

**Comment by 5d100** [comment]
that works. i second that one.

**Comment by Zefferis** [comment]
I think the general idea is that if the owner of the chest disappears for over 2 months, then the chest itself becomes open for anyone to view, use and take items from - and in this way it isn't necessarily griefing, rather its reclaiming unused items from an inactive player if they stumble upon some sort of deserted area.

I think the same should apply to things like locked iron doors or fence gates and the such.

I think it could go one of two ways, one is limiting the lock command to only within sponged regions where you have the ability to modify blocks, or to the log-duration that removes sponges from the game after 2 months, and as that goes so does all of your locked blocks? (I believe that's the mechanic in place for the sponged regions)

**Comment by 5d100** [comment]
well, considering that if someone's sponges leave after two months, then it'll just be a "check for someone's name and remove their lock" thing

**Comment by Zefferis** [comment]
Yeah, that's what I'm thinking

**Comment by TemperrroniPizza** [comment]
As soon as they're gone for 4 months, or haven't been to that home in 4 months, then the chests are unlocked,
