### ISSUE TITLE
Slightly Larger Mining Limit

### ISSUE THREAD

**Issue by Russell1992** [drewhoener/JWSuggestions#149]
I honestly think that the 55 Diamond Ore Mining Limit is alittle small. If it is possible could we up it to 60 or 65?

**Comment by drewhoener** [comment]
why?

**Comment by 5d100** [comment]
i personally think that 60 would be a great number. it just feels better than 55.

**Comment by TemperrroniPizza** [comment]
The only reason that this is here is to prevent people from stealing from the world via X-RAY mods. Which is beneficial to us all, while giving us some leeway.

**Comment by Russell1992** [comment]
I understand why we have an mining limit to prevent x rayers from getting all the diamonds but sometimes, us shop owners would like to get some extra diamonds for our shops.

**Comment by drewhoener** [comment]
is the number not 60? Well that just bothers me xD I'll bump it to a stack instead

**Comment by TemperrroniPizza** [comment]
I think it was 55 or something like that. But thanks for making both parties satisfied. I wanna do my part as a good community player, and try to help the staff a little bit as a player. Not too much, but just a smidgen
