### ISSUE TITLE
Ocarina of Time????

### ISSUE THREAD

**Issue by 5d100** [drewhoener/JWSuggestions#150]
Now, the idea comes from Ocarina of Time, and it's sequel, majora's mask. i digress, we should have an item that calls a certain horse that you tag. It'll be like, "you go somewhere, and realize, i want to bring my horse with me." then boom! you have your horse.

**Comment by TemperrroniPizza** [comment]
I would add to this by making a cache of what players named their animals, and what animals that they have tamed. And just register them under the command, for example: /ocarina add "Name here" and then right click on the certain mob. Then do /ocarina "name here" and poof there it is.

**Comment by rockerjman222** [comment]
correct me if i'm wrong, but if lockmobcapture is still a thing, then that has the same functionality as you just carry an egg with the horse inside.

**Comment by 5d100** [comment]
well, that's true, but if you use the /lmc the horse's speed changes.

**Comment by drewhoener** [comment]
There's no part of the API that lets me get their speed

**Comment by 5d100** [comment]
that's part of my point. also, you may have forgotten your horse and forgot to /lmc as well.

**Comment by drewhoener** [comment]
and what if you ALSO forget to set them on your ocarina? At what point are we just adding a new feature that exactly mirrors something that already exists? I feel like we have to draw a line somewhere.
(Disclaimer: I love Majora's Mask and OOT)

**Comment by drewhoener** [comment]
Oh I feel like I should clarify: If I use the ocarina idea, I'd be storing the data and respawning it elsewhere, I STILL wouldn't be able to get the speed

**Comment by rockerjman222** [comment]
So until spigot gives us a way of checking the speed of a horse, sadly things are going to have to stay as the way that they are.

**Comment by 5d100** [comment]
wrong. the speed of the horse doesn't matter. all you would have to do is transfer an entity to another place.

**Comment by drewhoener** [comment]
but I don't know where the entity is, I can't just find a single horse out of thin air, they aren't named and numbered.

**Comment by 5d100** [comment]
that's why you have the command. it would add a ping to the horse if that is how it works and just treat it as an entity.

**Comment by drewhoener** [comment]
> add a ping to the horse if that is how it works
It's not though
