### ISSUE TITLE
Creative world? Or another Gamemode?

### ISSUE THREAD

**Issue by TemperrroniPizza** [drewhoener/JWSuggestions#152]
Name: k_6
Idea: If resources are inhibited with your server already for another server like creative, close this. But I would like to see a new gamemode added to the server. This server has been up for 3 years, and has had not one extra, non-modded, server to play on. If Survival/Hunger Games can be introduced, or a creative server can be introduced, or kitpvp. I can supply maps. My friend FierceNinja makes server maps, or talk to the Kwa, who makes server maps, or even contact me. (Unlike them, I'm free. c:) Seeing a new gamemode would be cool, or could you devs add a minigames server, with new games. like Slime soccer, or turf wars, maybe minestrike, or block hunt. I'm suggesting.

**Comment by TemperrroniPizza** [comment]
Oh correction: The server has another server, the hub ;D

**Comment by rockerjman222** [comment]
We are currently in the process of developing new servers.

**Comment by TemperrroniPizza** [comment]
@rockerjman222 thank you I just noticed that you guys are working on the splegg plugin, and so far as I can see, it's looking very well done. I borrowed the code and ran it on a test server, and it works just fine. Good job you three.

**Comment by drewhoener** [comment]
Bullshit you borrowed my code, no one has access to my FTP key except myself and johnny nice try though

**Comment by TemperrroniPizza** [comment]
@drewhoener I was joking, but I know you guys are cool people, and the stuff you guys make are gonna be cool, so I'll stay out

**Comment by TemperrroniPizza** [comment]
You guys have done good jobs in the past, and I have run alternative splegg programs, to not only understand what the game is but, to generate a good idea of what you guys are gonna do. And I did borrow the code, there is something called opening a second window and viewing everything you guys have done. I didn't steal anything, I gave you guys credit anyways. I'm not a cruel person, I'm a 16 year old highschool student that pranks his dad with malicious viruses. It is a good splegg system. Something different, and I hope it turns out well. Good luck guys, and happy developing.

**Comment by drewhoener** [comment]
@TemperrroniPizza 
> And I did borrow the code, there is something called opening a second window and viewing everything

Uhhhhhhhhhhh. I thought I put above let's not be ignorant. That's not how File Transfer Protocol works, first of all...Second of all that's DEFINATLY not how encryption keys work: if you don't have my private key, you can't authenticate

Third of all, the code is on the test server, a server whose IP you have absolutely NO way of knowing, and NO way of accessing, yet you continue to try and convince people that you're able to do things that you clearly are not able to do
