### ISSUE TITLE
Buy Abilities

### ISSUE THREAD

**Issue by Violaessence** [drewhoener/JWSuggestions#157]
Basically, the idea is to replace commands like ./fly and ./god with buyable abilities, so instead of infinite god mode, you could buy god mode for a limited time, same with fly, the general idea is to allow players who purchase these ranks to have those abilities but to prevent them getting bored with the server once they have them, they simply buy fly for a certain amount of time, this gives those players incentive to get more money.

the system at the moment is pretty OP (OverPowered) to donators, I understand they support the server and should receive perks, but stuff like God Mode really takes the fun out of the game so i think that buyable alternatives will make the game fun for those players, whilst still giving them those perks

**Comment by TemperrroniPizza** [comment]
Think about it, Lord donators donate $100 to the server. That's a lot of money for a small server, and they have every right to their perks. Although you do make good points, They paid money for those in the first place. It's considered a little unfair if you have to donate for more time for perks they already have access to now.

**Comment by TemperrroniPizza** [comment]
I'd suggest to give it to the non donators but keep it in ingame currency.
