### ISSUE TITLE
Angry Easter Bunny Suggestion for Easter

### ISSUE THREAD

**Issue by 2scoopsrice** [drewhoener/JWSuggestions#16]
Hello, Its me again. I'm here to show my Idea, Which you can tell from the Title,  I have a new Idea for Easter! I call it the Angry Easter Bunny.  It would be a Killer Rabbit of Caernabog (If that is how you pronounce it...) That would be about as rare as the leprechaun now, and would only spawn in flower forests, or plains biomes. It would have a big chance of dropping random spawn eggs, and a really rare chance of dropping an (This is optional) Easter Bunny Egg, Which would fight for you if you spawned it in by throwing eggs at enemy's to distract them, it has 10 health. Screenshots:
![2015-03-17_18 34 18](https://cloud.githubusercontent.com/assets/11479867/6702752/584d9a56-ccd4-11e4-94bd-c71eb46660d1.png)

![2015-03-17_18 35 22](https://cloud.githubusercontent.com/assets/11479867/6702759/65ccfb54-ccd4-11e4-8dd3-e56a1396c738.png)

![2015-03-17_18 37 30](https://cloud.githubusercontent.com/assets/11479867/6702803/d77079fc-ccd4-11e4-94a6-5caee4cf91d1.png)

![2015-03-17_18 38 22](https://cloud.githubusercontent.com/assets/11479867/6702806/e46176ca-ccd4-11e4-9652-d16218a33002.png)

![2015-03-17_18 38 25](https://cloud.githubusercontent.com/assets/11479867/6702811/fcc9d554-ccd4-11e4-9669-e3b30f5b0062.png)

![2015-03-17_18 28 03](https://cloud.githubusercontent.com/assets/11479867/6702812/075e1be2-ccd5-11e4-83aa-d4f1e5b6edf2.png)

![2015-03-18_14 26 46](https://cloud.githubusercontent.com/assets/11479867/6722305/8f36ccf2-cd7b-11e4-84cc-b2114fede3f6.png)

Here you can see, The Angry Bunny and the (Again, Optional) Happy Easter bunny side by side, the little amount of support that i have for right now, what the Happy Easter Bunny spawn egg would look like, and the possible drops. Drop Stats:  This is the same for my other suggestion page. <number>100 is how often you would get that item out of 100 times.  5/100 for the (optional) Happy Easter Bunny egg. (Forgot to mention above, you can right click the bunny to make it sit and again to follow you. Doesn't have to be an animation or text or anything. Sorry devs if I'm making this too complicated, again this is optional. ) As well as having a chance of dropping the Happy Egg,  It has a 100% chance of dropping a normal rabbit egg. Now for other eggs, lets put it this way. The more hostile and difficult the mob, the more uncommon and less plentiful it becomes. for example, you would get 3 zombie eggs far more then if you got 1 zombie pig-man egg. (because honestly, Zombie Pigmen are a force to be reckoned with and we all know that.)  Passive mobs are 50 percent more common to drop then hostile. Cows and pigs are more rare then sheep and chickens, because their cooked food does more hunger points. Thank you for reading, and if you need to be clarified about something just let me know in the comments. Thanks!

**Comment by drewhoener** [comment]
Minecraft's Killer Rabbit is actually really difficult from what I understand, not sure if that's a thing we want in the game. Since rabbits aren't hostile naturally, it would be difficult to make them attack anything, but it might be possible.

**Comment by 2scoopsrice** [comment]
Yes, But couldn't you somehow make the rabbit spawn with a leather boot or something that gives him minus health and makes it down to 10 health, and what I am thinking is spawn a snow golem and somehow edit it to throw eggs instead of snowballs, and spawn it invisible riding the rabbit.

**Comment by SonOfDeath** [comment]
I dont think that is possible... I may be completly wrong

**Comment by 2scoopsrice** [comment]
I assume the amazing devs could use some wizardry and push some buttons to fix it.

**Comment by drewhoener** [comment]
Unfortunately I don't think it's really a viable option, especially for the amount of work it would require, just to be used for one day of the year

**Comment by SarabiMami** [comment]
Just gonna point out there is already a mod out there does something similar. It's an Easter Mod with an Easter pig. It spawns random mini blocks throughout the world, they are breakable and drop random goodies. Very rare drop will drop a spawn egg. The spawn egg is the Easter pig, when you spawn it says easter pig above his head . He lays (chicken looking) eggs occasionaly which are more place then break easter eggs.  I don't know if this Mod could feasibly be edited to work for this but it's pretty close. Still might be too much work for one day. But you could always do holiday weeks, especially considering players are from so many timezones, assuming it wouldn't alter the economy too much.

**Comment by 2scoopsrice** [comment]
Again, just spawning a normal killer bunny with random spawn eggs would work. the happy bunny thing is just optional.

**Comment by SarabiMami** [comment]
Normal killer bunny is hard to kill. Hopping death not easy to hit.

**Comment by SonOfDeath** [comment]
I'm guessing you haven't fought herobrine...

**Comment by Spazgazum** [comment]
I didn't know herobrine was a 1 block tall mob that hops. Lol

**Comment by SonOfDeath** [comment]
Lol no, herobrine is a hard boss tho :) that's what I was trying to say.

So Sarabi its going to be very hard to kill if it gets added.

**Comment by Spazgazum** [comment]
Yeah. He seemed hesitant to add it because of its difficulty. And yeah she's killed Herobrine quite a few times ( we hang in the nether often after mw reset )

**Comment by Spazgazum** [comment]
What if (and I'll try to make this sound soooo much easier to do than it is. Lol)...

Anyways What if instead of actually making normal bunnies hostile could you assign a damage amount to them and make them think that everyone has a carrot in their hands. Then its a natural follow and if they touch you it hurts.

Possible? Idk 
Just an idea. Lol

**Comment by SonOfDeath** [comment]
I don't think that's possible but drew would confirm :)

**Comment by Spazgazum** [comment]
Exactly, but... who knows.....




Who knows? Drew knows. Lol yay lame rhyme.

**Comment by johnnywoof** [comment]
The angry easter bunny with drops and rare spawns is a good idea. The rest, where you can summon a rabbit to have it fight for you (kind of went tl;dr so correct me if I missed something), is probably something that will not happen unfortunately, due to the amount of effort required for only one day of the year @drewhoener said.

**Comment by 2scoopsrice** [comment]
Yes, I understand how difficult it would be to make a normally non hostile mob. but like I have said multiple times, it would be optional and only added by choice.

**Comment by johnnywoof** [comment]
Added! It'll spawn in flower biomes at night, having a very rare chance. Drops an egg and a random colored dye.
