### ISSUE TITLE
Disallow Public Villager Farms

### ISSUE THREAD

**Issue by Violaessence** [drewhoener/JWSuggestions#161]
I believe that public villager farms should be made illegal along side the No Drop parties rule. and i will explain in full detail why below:

Public Villager farms are damaging to the economy in the fact that the items are notoriously cheap, you have such things like nametags and enchant bottles all which can be classed as rarity items which can be obtained through villager trading. 

Of course that's not the full picture i will go on about the Mending and Frost Walker argument.

I know that red is increasing the price of Mending and Frost Walker books through villagers however it's still damaging to have public villager farms because the prices are then permenantly the price of that villager's emerald trade. 

On Johnnywoof 3.0 the emerald price at ./warp topshop is 20 coins per emerald, meaning that if say a villager sells mending books for 10 emeralds, the price of that mending book is now 200 coins to get, but it will never raise or lower, it will ALWAYS be 200 coins because it has no reason to raise or lower, before i saw mending books rise and decrease in price before and after mineworld was reset, people would sell mending books through end cities, and the way villager farms worked was that you personally owned a farm that could get mending books and sell them for that price, but trust me when i say the rarity of a mending villager alone and the materials needed to get one cost alot of money.

So when i had my mending villager yes i could sell the mending books for alot of money, so could others, everyone had the chance to, but the problem came that when you make a farm public you create a fixed price for a book, if you have a mending villager sell for the lowest a villager sells them, you could sell mending books for 200 coins, effectively making going to the end or even making a villager farm of your own.. worthless. 

Some people say that this is to help out the new people, but to be honest i think it's more akin to a drop party and giving away a free item, it helps people sure, but it also downed the price of that item by over half the original value, which isn't fair given that it was a treasure item. 

Villager farms are very OP, i will be the first to admit that, and that's the reason why i believe Public Villager farms are a danger to the economy, giving away the OP villagers to others is a way to down the price of items, and eventually no one will be able to compete with the price because villagers have a lowest price they will sell for in emeralds, if you make that villager available to the public you've bottlenecked the price for good, because no one will be able to compete with that price, and thus that item is then worthless to sell. which is not good for the economy.

**Comment by drewhoener** [comment]
For all intents and purposes, this is unenforcable. I think you're making good points saying that people should have to work for their villager trades instead of reaping the benefits of someone's work but I have no way to enforce this

**Comment by Violaessence** [comment]
I understand that, Thank you for reading my suggestion :)

**Comment by Selttiks** [comment]
If i may comment, the same could be said about public grinders. When and where should the line be drawn?

**Comment by Violaessence** [comment]
Public Grinders give only really.. a few types of items, like Blaze Rods/Rotten Flesh/Arrows & Bones

These things aren't really going to make a significant impact in the economy anyway, because people sell stacks and stacks of them

If you somehow downed the price of Blaze Rods, it wouldn't make a difference because they're generally a cheap item on the server anyway, same could be said for bones/arrows/rotten flesh etc

**Comment by Selttiks** [comment]
Public exp farms do the same. you work off of other people's work to get the spawners so they can farm coins and items off of mobs. Which then drops the price of enchanted items, because everyone can get exp easily. You have to work to get emeralds, whether grinding items to trade, or mining them. or buying them, which you either get from grinding mobs, or voting. You work equally as hard for the loot from villagers. You just dont have to hunt down the villagers.

Same goes for the exp farms. You dont have to go out and get 20 spawners. You go use someone who has gotten the spawners. In fact, it takes more time, or money, to make a public spawner grinder, than it does to get villagers. If anything, the public exp farms are worse.

Where should the line be drawn? You are ignoring the fact you get coins from killing mobs.

**Comment by drewhoener** [comment]
And again, how do I enforce this?
Prevent any warp that's within 20 blocks of a villager? I don't think so
The part that I'm hung up on is that while I can agree with the villager farm aspect, I don't know how to effectively do it
Am I supposed to have staff patrol every portal in a shop in addition to their monthly inspection? And even if I did, that's still only once a month
It gets to the point where I have to question if it's even worth putting the resources into
