### ISSUE TITLE
/block

### ISSUE THREAD

**Issue by TemperrroniPizza** [drewhoener/JWSuggestions#165]
Name: pop_bob
Idea: /block
This will change ores into blocks if smelted. For example, if you have 9 diamonds, and do /block, it turns the diamonds into one diamond block.
Benefits:
-If you have an Efficiency 5 pick with Fortune 3, and Conflagration, and you've collected ores, presmelted, do /block and it saves space instead of using a workbench and stopping your mining session.
-Saves tons of time.
-It's a straightforward name for a command, so it's easy to remember.
-It's easy to make, and basic to code.

**Comment by drewhoener** [comment]
Really? If it's so easy to make, how would you code it?

**Comment by johnnywoof** [comment]
Suggestion coded and tested.
It will be deployed on the server upon the next update.
The command has been changed from /block to /iblock

**Comment by johnnywoof** [comment]
Deployed.
