### ISSUE TITLE
Auto-lock turn on and off

### ISSUE THREAD

**Issue by PianoPlayingHusky** [drewhoener/JWSuggestions#166]
IGN: Kkhaebsong

There can be a command for turning auto-lock on chests, furnaces, etc on or off

This will be useful because some players make storages to use with other players but adding each of them to the chests are too time-consuming.

**Comment by drewhoener** [comment]
@PianoPlayingHusky if it's too much work adding them all you can always do /unlock, it's not much work at all. Sorry but it's not quite worth the time xD
