### ISSUE TITLE
Exclude Dragon Eggs from ./s

### ISSUE THREAD

**Issue by Violaessence** [drewhoener/JWSuggestions#167]
Simply put, Mineworld resets every week, and with it a new egg spawns once the dragon is killed, my suggestion is that the dragon egg is excluded from the ./s command to make it fairer on everyone wanting it, that way it isn't just epic/lord donators getting the eggs due to the advantage of instabreak

**Comment by drewhoener** [comment]
People are welcome to respawn the dragon to get their own, I nee to remove my sponge however

**Comment by johnnywoof** [comment]
Reopening issue due to @Violaessence claiming that re-spawning the ender dragon doesn't create a dragon egg.

**Comment by Violaessence** [comment]
The Respawning of an Ender Dragon via Ender Crystals will not give another egg once the dragon is slain, which is why each week an egg can be claimed, with alot of people gathering around to kill it, Epic/Lord donators have an unfair advantage at getting the egg above the rest which is why i believe it would be good if it was exempted from ./s which gives everyone a fair advantage of getting it.

**Comment by drewhoener** [comment]
This is done
