### ISSUE TITLE
Sub-Areas inside Protected Areas

### ISSUE THREAD

**Issue by Violaessence** [drewhoener/JWSuggestions#169]
Simply put a command to be able to specify an area of a protected area for different people to be added or different flags to be set, this allows for people to be added to one area without access to another area, and allows for things such as grinders to have no Mob-AI and another part to have Mob-AI or one part not allow homes to be set and another to allow them. 

This allows for much more thorough customisation of Protected areas.

**Comment by drewhoener** [comment]
I'm putting this one on the back burner since I'd have to rewrite most of my existing sponge code, and it would change the way regions are saved so we'd have to wipe all regions to update
