### ISSUE TITLE
Mining Limit Placed Ores

### ISSUE THREAD

**Issue by SarabiMami** [drewhoener/JWSuggestions#17]
Hello Lovely Staff People!

 My suggestion is that PLACED precious ores not count as part of the mining limit. I prefer to silk touch my ores and mine them later in the safety of my own home. I often mine all day, go home and fortune my ores. However on many occasions i hit my mining limit while fortuning them. Often there are not mods on to reset the limit when this happens in the middle of the night. plus i feel bad asking to rest my mining limit as i dont want to be unfair or impose on the busy admins. I do not like to tempt fate by fortuning ore while out, because catching one block is a lot easier than a bunch of pieces. I would hate for them to fall in lava or lag out. Also doing this helps me keep track of my ming limit for the night and saves inventory.  I know i'm not the only person who does this and i know it is possible to tell the difference between placed and notplaced, as that treecapitator and other tree mods recognize the difference between placed wood blocks and a tree and are customizable.

Thankyou for your time. :)d

**Comment by SonOfDeath** [comment]
This is an interesting suggestion.

"Hello Lovely Staff People!" I'm flustered but not everyone here is staff :3

"in the safety of my own home" What would be the dangers of mining in a mine? I mean if you're already mining things with silktouch why would mining it later decrease the risk? 

"to be unfair or impose on the busy admins" Don't worry about that honestly, all they have to do is insert a command to reset your mining limit.

**Comment by drewhoener** [comment]
As far as I know from testing (at least for diamonds) I don't think it counts to your limit if you're above level 20 or so. I could be wrong though

**Comment by SarabiMami** [comment]
I believe I already answered your question in my post SonofDeath. 
Also while thereally are obviously other people reading these besides staff, staff will be the ones having final say on suggestions so I directed it towards them out of respect. 
Furthermore it's not a worry,  I'd just rather not have to ask. I don't mind waiting on it to reset, it makes the game feel more fair to me. As super mining is very op. But i'd rather not waste my limit on my own material.

**Comment by SarabiMami** [comment]
Red, thanks for telling me that. It must not be common knowledge  because a couple people didn't understand why I couldn't mine my own ore. BUT now that you say that, my storage does begin on bedrock which is where I placed my ore to break them this time. (I don't usually break them there.)
Still it would be nice if the placed ore would be separated overall, however I don't know how much work or hiccups  it would be; and I understand if it won't be a thing.

**Comment by drewhoener** [comment]
To do that, I'd have to log every block of ore ever placed by a player, and then whenever a block is broken, I'd have to check it against that list, which is very intensive. Overall I don't think it's worth it to do it.

**Comment by SonOfDeath** [comment]
I'm still confused.. Why would you mine (something like) diamond ore with slik touch, then take it to your home and mine it there? Wouldn't you lose pick durability faster?

**Comment by drewhoener** [comment]
Yeah, but you can carry more if you silk it. Better to have 1 stack  lapis ore than 7 stacks loose while mining

**Comment by Spazgazum** [comment]
What he said. Compact is always better. Also we like to save and stock up on ore and break only the ones past a certain amount. So when we make a shop we have a good supply of both ore and materials.

**Comment by johnnywoof** [comment]
As long you mine ores when y > 20, it will not count for your mining limit.

**Comment by Spazgazum** [comment]
That's fine. Knowing the y>20 limit pretty much solves the problem anyway. Thanks
