### ISSUE TITLE
Unique Enchants for Picks

### ISSUE THREAD

**Issue by Violaessence** [drewhoener/JWSuggestions#170]
My idea is fairly simple it simply provides reason to grind and enchant different picks for different Unique Rare enchants.

My ideas are as follows

Diamond Pickaxe: Rare Enchant = SpawnerPickup (Already Implemented) Can't Be Repaired [Not My Idea]

Gold Pickaxe: Rare Enchant = Wisdom (Implemented on swords but gives 2x Exp Drops from Ores) Can Be Repaired

Iron Pickaxe: Rare Enchant = Compressor (Gives chance 1/5 to drop a block and not a single ingot or gem for example a mined diamond ore would have 1/5 chance to drop a diamond block instead of a single diamond, if it drops a block the pickaxe takes 20 durability damage) Cannot Be Repaired

Stone Pickaxe: Rare Enchant = Super Conflag (Rare version of conflag which gives 2x ingots from ores) Can't Be Repaired 

Wooden Pickaxe: Rare Enchant = DoubleDrop (Provides Double Drops for ores, Stacks with Fortune) Can Be Repaired

Note: All these enchants have the same chance of been obtained as SpawnerPickup

**Comment by drewhoener** [comment]
how is spawnerpick your idea?

**Comment by Violaessence** [comment]
it is not, i am however giving a reference to how the enchants work as unique to the different pickaxes

**Comment by drewhoener** [comment]
shutting down compressor, not giving a 1/5 chance to give anywhere from 3-9x as many resources
conflag has a chance to give double when used with fortune

**Comment by Violaessence** [comment]
what about the gold and wood pickaxes?

**Comment by drewhoener** [comment]
ores only give 1/10th of the xp of a blaze (and that's at diamond level, everything else is worth much less in terms of xp), wisdom never seemed worth implementing for pickaxes, especially at that rarity

**Comment by Violaessence** [comment]
what about making them give a level of exp that would be worth getting it say.. 1 ore = 4 blazes exp if that makes sense

**Comment by drewhoener** [comment]
but why would I do that
go kill some blazes

**Comment by Violaessence** [comment]
hmm.. what about the wood pickaxe?

**Comment by drewhoener** [comment]
wood is basically compressor, if it stacks with fortune, if you get 3 diamonds, then it multiplies to 6. It just seems like a cheap ploy for resources, even if it is rare, and there's no real need for it
Unfortunately the suggestions aren't really worth implementing for those reasons, and while I love coding new enchants, I'd rather code something that adds real features and not just multiplying resources, which in my opinion shouldn't be something that we add in the levels that you're suggesting
