### ISSUE TITLE
Safe Space

### ISSUE THREAD

**Issue by Violaessence** [drewhoener/JWSuggestions#174]
Your Minecraft username: Violaessence
Your Request: ./Safespace Command
Why you think changing it would make the server better/more enjoyable.

I believe that a ./safespace command can be used to automatically kick a user from the server at their request in order to preserve them from anything that they deem too much for them, if a topic is being discussed that they do not like or if something is said that they may find too much they can simply type the ./safespace command and be automatically kicked from the server in order to take a break.

Reasons this benefits the server:

1. It's faster than logging out which is very important in making sure the person who is being affected does not endure more than they have to.

2. It ensures they are now safe with the Message after being kicked been "It's Okay.. You're Safe now!"

3. It provides security in knowing that they have the command at their disposal if they need it, which is very important for those users who are not able to deal with the harshness Minecraft provides at times.

I believe this command will make it easier for users who need the security of a safespace and i believe it will make Johnnywoof a safer and better place for everyone if they have the security of ./safespace :)

**Comment by RebeccaAMGG** [comment]
1. logging off is quicker then typing out /safespace
2. theres no need for that on JW, the server has a nice community
3. red is probably busy coding other stuff atm and doesn't need more things to work on

**Comment by Violaessence** [comment]
There are alot of things on minecraft that are not for the faint of heart.. You have to understand some people need to be comforted if they are confronted with a situation on minecraft they deem to be too much and safespace allows them to be comforted and reminded that they are safe.. :)

**Comment by drewhoener** [comment]
Thanks/no thanks for the sarcasm/satire, post helpful things in the future? My eyes get tired when I read
