### ISSUE TITLE
/back problems

### ISSUE THREAD

**Issue by SonOfDeath** [drewhoener/JWSuggestions#19]
(I'm making this because Drew told me to :p )
/back has some bugs when you're underground, for some reason if you leave a place underground and you try to do /back you will spawn on the surface to where you were.

For Ex.
If you left X 175, Y 5, Z 90 (random numbers) and you try to /back to get back there you will appear at X175, Y 50, Z 90.

This can be annoying when mining, or when you have a secret underground base.

**Comment by Spazgazum** [comment]
As this is normally the case, sometimes it can also take you to around the same height level, but moved over a good bit on one of the other coordinates. But this seems more common in natural structures, like mineshafts or caves and things where the above ground spawn seems to occur more when just mining. At least from what I've seen.

**Comment by johnnywoof** [comment]
Fixed. Awaiting deployment.

**Comment by johnnywoof** [comment]
Deployed.

**Comment by Spazgazum** [comment]
Awesome. Thanks guys.
