### ISSUE TITLE
leaves

### ISSUE THREAD

**Issue by draelu** [drewhoener/JWSuggestions#2]
when u mine birch and oak trees the leaves instantly despawn. if possible make it so dark oak, acacia, jungle, and spruce leaves instantly despawn as well

**Comment by johnnywoof** [comment]
In minecraft, there is an enchantment called silk touch. If you have silk touch on a pickaxe, you will get stone instead of cobblestone when you mine stone. Since it already exists, we will not add it.

**Comment by Duraninator205** [comment]
So this will be in the
 server now?

**Comment by drewhoener** [comment]
If it has an awaiting deployment tag on it it will be, as of now it's not done

**Comment by johnnywoof** [comment]
Fixed
