### ISSUE TITLE
/trash

### ISSUE THREAD

**Issue by Spazgazum** [drewhoener/JWSuggestions#20]
I think /trash should be available to everyone.

Benefits.

No excuse for dropped items thrown around public places (Stores and public xp farms are bad with riddled with trash often, right Mel? Lol)

Downside.

Possibly more modreqs for people accidentally trashing the wrong items.

But with the option to just dump items on the ground I don't see why it would hurt to give /trash to everyone instead of just a donor perk. 

Thank for your consideration. -Spaz.

**Comment by SonOfDeath** [comment]
Its advertised as a donor perk so it will mostly stay like that.

**Comment by Spazgazum** [comment]
I understand that,  but /trash usually isn't enough to persuade a donation. (If you don't care enough not to dump trash all over sweetmart, then you probably won't care enough to pay rl money to get /trash.) 

 And I use sweet Mart as an example because I see trash dumped there all the time and sometimes causes major lag. But it's not just sweet mart (or the lack of trash cans) I also see it in public xp farms like nicoderms skeleton spawner, there's a trash can in there and people still will dump inventory on the floor so they won't lose their spot. 

Anyways. It would help the community more if everyone could use it by keeping lag down and stopping unwanted "free" broken item pick ups while walking through shops taking up your inventory slots while trying to but things. 

There are still enough perks to persuade donations without it, I believe.

**Comment by SonOfDeath** [comment]
If public trash cans are available and people wont use them..

What makes you think they will use /trash ?

**Comment by Spazgazum** [comment]
Well first off, this happens more often because of the lack of public trash cans. 

Secondly, it is much quicker and easier to /trash than go to a trash can in some places making it a more possibly used option.

And thirdly (and more to the response of your question), in the example I gave I used the skeleton spawner as a reference and said that they dump items as to not lose their spot. I don't really know of how many places With Trashcans that people still dump trash, I'm sure that it happens, but this is the only one that I've seen. And I've been in it before a few times before I donated where when I went to trash things in his trashcan people jumped in front of the spawner and I just left. So with /trash people could trash without fear of someone taking their spot.

**Comment by Spazgazum** [comment]
Hey, it's not a perfect fix..., but it could help.

**Comment by Spazgazum** [comment]
Could replace /trash with the death coordinates suggestion. That way death point could be a stepping stone to /back on the next donation teir.

**Comment by SonOfDeath** [comment]
I don't think this will be implemented because it is a donor perk. and there are a lot of trash cans, no one ever uses them tho.

**Comment by SarabiMami** [comment]
I see lots of people use the trash cans and you're really just repeating yourself.

**Comment by SonOfDeath** [comment]
I might be repeating myself, the only time ive seen people use them is when they're at spawners.

At the same time I see people teleport to spawn dump items and leave.

**Comment by SarabiMami** [comment]
I edited my comment, I wasn't done, my bad.

**Comment by SonOfDeath** [comment]
I personally do not think it would reduce lagg, people that care about putting trash away will go to trash cans, people that don't care will still dump things. 

They're lots of public XP farms, and in towns too there should be enough space for everyone
