### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by KiltedDemon31** [drewhoener/JWSuggestions#25]
There needs to be a grouping system in the game that is displayed in chat. Players can start them for a set amount of coin. It will increase interaction among players by helping them make friends within groups and It will make people want to join the "prestigious" groups that are made by players.

**Comment by drewhoener** [comment]
Could you provide an explanation of what commands would be part of this?

**Comment by KiltedDemon31** [comment]
I have to be honest I'm not much of a wiz with this kind of stuff so I dont even know if it is possible, but I know you have to separate players into different permission groups for the separate donor ranks. The only problem with using this that you'd have to give all players access to this command so they'd be able to add people to donor groups. 

You have a donor chat (/a) so their must be a way to separate donors from regulars.

**Comment by johnnywoof** [comment]
I like the idea of groups, and there is currently a system under development classified as a party system, which is very similar to your idea @KiltedDemon31 .

**Comment by johnnywoof** [comment]
Will be applied next proxy reboot.

**Comment by johnnywoof** [comment]
A stable version has been deployed.

Check the command */party* for details!
