### ISSUE TITLE
Enderdragon

### ISSUE THREAD

**Issue by SonOfDeath** [drewhoener/JWSuggestions#3]
The enderdragon (ED) is an awesome boss that drops a cool egg, why not be able to fight the ED every now and then? I mean we can already fight the wither so why not the ED?

I played on a server (Back in 2012-13) where the ED would spawn every week, which was good because it meet people could not farm the ED.

Its also friggen awesome when you and your friends can make a group to slay the beast!!!!!

**Comment by Duraninator205** [comment]
This would make some people made because they die and they can't get there stuff because /back costs 1k for them

**Comment by Duraninator205** [comment]
This should be a thing.....

**Comment by SonOfDeath** [comment]
I agree

**Comment by SarabiMami** [comment]
Yeah this would be great, i was disappointed this server doesn't have this setup.

**Comment by drewhoener** [comment]
Interesting...My primary concern is that the Dragon Egg (while completely USELESS), is still a rare item. An ender dragon per week can add up to a lot of them. I'm considering making them a rarer drop, just to keep it interesting. Would that work?

**Comment by SonOfDeath** [comment]
I got a better idea, make it so /fly and /god is not available in the end as well as a rare drop.

**Comment by OoveVolcae** [comment]
I love the idea, especially since it could open up a mine world End (thus saving the current End from further endstone exhaustion), but wouldn't items like the One Hit sword be too OP for it? I would -love- to face the Ender Dragon with some buddies on the server, but if people just head there with the One Hit then there's no challenge, no risk, and no rarity to the eggs anyway. I'd still love to see it, and definitely use it if it was implemented, but I'm not sure how it would work with other plug ins.

**Comment by drewhoener** [comment]
Not sure what you mean by other plugins, but the plugins we have on the server are made by us, usually we can adapt to whatever we put in

**Comment by hoogkerker** [comment]
1.9 will have this feature most likely so why be impatient and do so much work for something that is in development already

**Comment by Spazgazum** [comment]
Yep. Forgot to comment that, but he is supposed to be respawnable in 1.9.

**Comment by littletntman** [comment]
I think to have /fly & /god available is fair because you used your money for the rank.

**Comment by Duran1** [comment]
Best idea ever

**Comment by 5d100** [comment]
wait... could we do this and make it so that the dragon egg doesn't spawn?

**Comment by rockerjman222** [comment]
This has been implemented with the end mineworld
