### ISSUE TITLE
Save my sanity!!!

### ISSUE THREAD

**Issue by Pheonixx** [drewhoener/JWSuggestions#33]
idk about anyone else, but these hashtag spams are drivin me batty!!!! there is no real use for them, and as amusing as they can be, they only seem to cause drama in chat. so for the sake of my sanity, and others' im sure, can we please boot hashtags out the door?

**Comment by Spazgazum** [comment]
+1Thousand support

**Comment by SarabiMami** [comment]
Over 9000 support.

**Comment by johnnywoof** [comment]
Just for the record, @drewhoener coded them in not me. :P

**Comment by drewhoener** [comment]
gah, I was really proud of those, though it was more of an experiment... Should we even remove the different color of them?

**Comment by johnnywoof** [comment]
Anything hashtag related will need to be removed.
Which includes but not limited to the color changing and /hashtag

**Comment by hoogkerker** [comment]
I think # can just be allowed but the fact there is a /hashtag command which shows a top 10 makes it "competetive" for people maybe first remove that, if it doesn't help also the color changing

**Comment by OoveVolcae** [comment]
I would agree that recent spammers have ruined the hashtag function for all, but some still enjoy it. Isn't that purpose enough? It's just as much purpose as /woof and / meow when used properly.

I agree with Hoog that the /hashtag gets a little annoying, and I'd definitely support removing it. Why not put a timer in the hashtag function like the /me function?

If there's a way for members to enjo it without overdoing it then why not go that route? If te answer is that it doesn't have a use... Neither do /woof, /meow, colors, and often times nick names. All of which I've seen spammed, nick and color on a regular basis.

**Comment by johnnywoof** [comment]
All traces of hashtags will be removed on the next proxy reboot/restart.

**Comment by johnnywoof** [comment]
Deployed. Hashtags been removed.
