### ISSUE TITLE
3 useful/helpful commands

### ISSUE THREAD

**Issue by littletntman** [drewhoener/JWSuggestions#37]

**Comment by littletntman** [comment]
Today I have 3 useful/helpful commands.

-/getenchantment with this you can get a enchantment but the harder to get the more levels.

-/oremap this command shows you ore's around you in a 3x3 space.

-/repair or /fix fixes and item in your hand command for UltimateDonator+.

**Comment by johnnywoof** [comment]
None will be added.

-/getenchantment with this you can get a enchantment but the harder to get the more levels.
Arguably will break the enchantment system.

-/oremap this command shows you ore's around you in a 3x3 space.
Too op

-/repair or /fix fixes and item in your hand command for UltimateDonator+.
We decided not to add /repair
