### ISSUE TITLE
Fishing pole enchantment

### ISSUE THREAD

**Issue by hoogkerker** [drewhoener/JWSuggestions#38]
How about some custom enchantments for fishing poles?

<li><b>Fish cooker</b> - 1/10 - <i>Cooks fishes on catch</i> </li>
<li><b>Double hook</b> - 1/40 - <i>A catch doubler (might need a discussion on 2 the same items or both random)</i></li>
<li><b>Richrod </b> - 1/20 - <i>If it catches armor it always is fully repaired</i></li>

**Comment by littletntman** [comment]
I like these instead of swords and bows and armor it's for fishing rods

**Comment by drewhoener** [comment]
I really like these xD. I'm down, if no one has objections

**Comment by OoveVolcae** [comment]
I like them. How will double hook work? Just double what you catch?

**Comment by SarabiMami** [comment]
These sound pretty cool! I support it.

**Comment by mathshen** [comment]
Turn down for what. DISSS

**Comment by johnnywoof** [comment]
Deployed.
