### ISSUE TITLE
Conflaguration

### ISSUE THREAD

**Issue by SonOfDeath** [drewhoener/JWSuggestions#4]
When you mine stone you get cobble (Duh)
But make it so you get stone instead :D

**Comment by johnnywoof** [comment]
In minecraft, there is an enchantment called silk touch. If you have silk touch on a pickaxe, you will get stone instead of cobblestone when you mine stone. Since it already exists, we will not add it.

**Comment by drewhoener** [comment]
I don't think johnny understood what you were asking for. The conflagration enchant will smelt cobble back into smooth stone in the next version of the server software, will not be for a bit though
