### ISSUE TITLE
/Repair

### ISSUE THREAD

**Issue by littletntman** [drewhoener/JWSuggestions#41]
/repair is for donators and it will repair an item in your hand for 15  coins.

**Comment by Spazgazum** [comment]
Too cheap, (also seems like it could get op after a while). I would expect it to cost 50 maybe even 100 per fix. Tho maybe it could be a cost equal to lost durability. Like if a sword has 5% left before breaking then it would cost 95 coins or a base fee plus 95 coins.

Although I think I would prefer something more like /anvil than just /repair, but that may be just me. Lol.

**Comment by Spazgazum** [comment]
(And by that I mean a command to open an anvil, not just pay coins to fix) Just to clarify. : )

**Comment by johnnywoof** [comment]
Not adding it.
https://github.com/drewhoener/JWSuggestions/issues/37
