### ISSUE TITLE
PVP arena 

### ISSUE THREAD

**Issue by mouldya** [drewhoener/JWSuggestions#43]
I (Mouldya) was thinking it would be beneficial to the server to add a PVP arena. it will please both crowds. and get more people on the server.

**Comment by johnnywoof** [comment]
Honestly I see more trouble having a pvp arena. Many complaints about dieing and other things.

This has been suggested many times, and unfortunately it has been rejected.

**Comment by mouldya** [comment]
You could set it up to be a completely different inventory so nothing is
lost from survival
