### ISSUE TITLE
/Jukebox

### ISSUE THREAD

**Issue by 2scoopsrice** [drewhoener/JWSuggestions#44]
This would be a pocket jukebox, essentially. you would run a command and it would start playing that song, but only you would be able to hear it. it is only for pro donators and above, and would play and jukebox music disc. an example of this command is /Jukebox cat 1000 (1000 is the amount of seconds it will play. If it is longer than the whole song, it will just loop. if it is shorter, it will be abruptly cut off.)

**Comment by johnnywoof** [comment]
Unfortunately this is not possible, due to the way on how minecraft physics work.
