### ISSUE TITLE
Towny: Bank interest

### ISSUE THREAD

**Issue by stefan3140** [drewhoener/JWSuggestions#46]
Stefan3140

I came up with the idea to add an interest on the town bank, because towns are incredibly expensive, it would be usefull the make the interest 1% on the town bank only. And to prevent that people make a town just for the interest, we could add that the mayors can only withdraw 2k/day from it.
If you could add this, towny would be much more enjoyable, it will still be a challenge but it will be at least possible! Ty for reading this, and if added, ty for your time!

**Comment by JensieXD** [comment]
Great Idea!

**Comment by Galedyr** [comment]
I like an idea but I have a suggestion to it: Maybe make this a privilege towns have to earn so players don't abuse it.

**Comment by danieldo24** [comment]
Great idea they should add it :+1:

**Comment by johnnywoof** [comment]
Sounds like a good idea.
@drewhoener

**Comment by drewhoener** [comment]
@johnnywoof on it

**Comment by johnnywoof** [comment]
1%

**Comment by SonOfDeath** [comment]
That's a little high

**Comment by stefan3140** [comment]
I agree that 1% is high IF towny wouldnt be 10x expensiver then 2.0, so for 3.0 1% isnt high at all.

**Comment by JensieXD** [comment]
I agree with Stefan, towny is way more expensive than JW 2.0 so I think 1% would be fair.

**Comment by drewhoener** [comment]
Well it's .1% right now, let's see how it goes
