### ISSUE TITLE
Something Useful for Herobrine Heads Like a Wither Brine :)

### ISSUE THREAD

**Issue by Lephhyre** [drewhoener/JWSuggestions#48]

**Comment by johnnywoof** [comment]
Please explain

**Comment by Spazgazum** [comment]
Herobrine heads plus obsidian to spawn a giant Herobrine?

**Comment by Lephhyre** [comment]
Ok well I really want something a reward for getting herobrine heads at this point and time on the server the herobrine heads don't really serve for much besides wearing them on using them as decorations which is kinda useless at this point so I think like after collecting a certain amount of herobrine heads you should be able to like make something very similar to the wither but a herobrine instead making it drop farely rare stuff like maybe diamonds or something or maybe the herobrine heads can craft like  a sword or something im not really sure where I was going with this but I just want some implemented with the herobrine heads :/

**Comment by stefan3140** [comment]
I agree that herobrine Heads are kinda usefull atm. They should really add a giant Herobrine Boss, seems funny to kill with a team or something.

**Comment by drewhoener** [comment]
Giants are their own type of mob, it's not like I can just apply a skin to them, unfortunately. I do love your idea, but it's simply not possible. As for a reward, you do get 200 coins though

**Comment by 5d100** [comment]
we could make nine of them turn into something that can spawn a herobrine into the build world. they wouldn't be attackable or anything like that, but they would be there for kicks and giggles.

**Comment by johnnywoof** [comment]
The herobrine head and the 200 coins are satisfying rewards in my view point. I don't think they need anymore.
