### ISSUE TITLE
/firework

### ISSUE THREAD

**Issue by jkopp415** [drewhoener/JWSuggestions#50]
I am jkopp415 on the server, and my idea is to have /firework in the server. For Ultimate Donater and higher, they could say /firework [green] [orange] [red] [yellow] [blue] [purple] and it would spawn a basic firework with the color of their choice above their head. This could be useful because for most players it is hard to craft fireworks, and with this they could also make neat shows for their friends. Note: this would launch the firework and not spawn it in their inventory, and it would have a 5 second cooldown.

**Comment by drewhoener** [comment]
There is already a custom item in /buytemp that will spawn tons of fireworks and it doesn't cost much money. Also, this would qualify as just spawning items without cost, which is something we don't do
