### ISSUE TITLE
/breath (/b)

### ISSUE THREAD

**Issue by jkopp415** [drewhoener/JWSuggestions#51]
It is jkopp415 again, and I have an idea to make a /breath (/b) command. When you are underwater and your air bubbles are almost out, for Epic Donaters or higher, you could use /b and it would replenish your bubbles. It is very annoying for players when they have to keep coming up for air when they are working underwater. This command would make it easier for a lot of players.

**Comment by drewhoener** [comment]
With a respiration III helmet, breathing time is significantly increased. In addition, you can always use a bucket or torches to create a pocket to get more air time. For these reasons, I won't be implementing the command
