### ISSUE TITLE
A way to view your own rank's perks on the website.

### ISSUE THREAD

**Issue by Waffleflappers** [drewhoener/JWSuggestions#52]
There needs to be a way to see the perks of the rank you currently have on the website, rather than just the perks of the ranks that are ahead of your own.

**Comment by drewhoener** [comment]
http://johnnywoof.net/donatorperks.php

**Comment by Waffleflappers** [comment]
I knew I was going to end up making a suggestion on something that already existed, I apologize for wasting your time.
