### ISSUE TITLE
Lockable Boats

### ISSUE THREAD

**Issue by Waffleflappers** [drewhoener/JWSuggestions#53]
There should be some way to lock boats. I don't know is that's something that is codable, but I will suggest just in case. It is annoying when I put a boat out for decoration and someone hops in it and rides around smashing all of my Lillypads, then breaks the boat and leaves. There is nothing I can do about it either.

**Comment by SonOfDeath** [comment]
Maybe instead of being able to lock the boats.. Why not add a sponge flag and you can let things be mounted on of not

**Comment by johnnywoof** [comment]
I like @SonOfDeath 's idea, a sponge flag.

**Comment by johnnywoof** [comment]
Deployed.
