### ISSUE TITLE
Sword Enchantment - rbnharper (internet problems)

### ISSUE THREAD

**Issue by NightHawk164** [drewhoener/JWSuggestions#55]
This was suggested by rbnharper, not I

Stormringer - Has a chance to summon lightning for charged creepers

Reason: If you used charged creepers you can get any head of a mob, hense wither skulls.
Rarity: Pretty Rare and with like a 30% chance of it working

**Comment by johnnywoof** [comment]
I like the lightning idea, but not the charged creeper one.

**Comment by MetroUniverse** [comment]
I Have Two Idea
#1. Frost, It Makes Your Target Slower And Prevents it From Jumping, But Fire Apect Cannot Be used
#2 A.I. Reverse- It  Does No Damage To A Monster  But Makes It Attack Other Monsters, 1/75 Chance And CANNOT BE REPAIRED

**Comment by MetroUniverse** [comment]
I Have Another suggestion
One Hit Is Already Way To OP, So I Thought Players Would Have To Make A Sacrifice, RRename It No EXP and it has the same effects as one hit but you dont get any exp,

**Comment by draelu** [comment]
another possible sword enchant would be one that gives u either double coins or 1 extra per kill

also not a sword enchant but a modification to a pick enchant making veinminer work with fortune would be nice

**Comment by johnnywoof** [comment]
Due to further consideration, I decided not to add it.

**Comment by drewhoener** [comment]
@MetroUniverse if you have suggestions different from those in a ticket, please make your own
