### ISSUE TITLE
Auto-Leaf Breaking

### ISSUE THREAD

**Issue by KnittingPaws** [drewhoener/JWSuggestions#58]
I miss this soooo much. I know I ask about it in chat a lot so figured i should make it official. Please bring it back :)

**Comment by johnnywoof** [comment]
The main reason why it was not brought back is due to the performance overhaul. Though if we can find an efficient way make it happen, it'll make a return.

**Comment by KnittingPaws** [comment]
that would be awesome cause it was my favorite fun feature of the server :)

**Comment by draelu** [comment]
this by far was one of the major reasons why i chose to make this server my home and the reason why i donated

**Comment by KnittingPaws** [comment]
same for me. i want to upgrade to lord donator but am waiting for this to be fixed first

**Comment by BlueKnightSam** [comment]
Isn't this done @johnnywoof or @drewhoener

**Comment by johnnywoof** [comment]
Added
