### ISSUE TITLE
Enchantment for armor that adds Hearts

### ISSUE THREAD

**Issue by SlimeBoyPlayer** [drewhoener/JWSuggestions#59]

**Comment by johnnywoof** [comment]
Please explain.

**Comment by NightHawk164** [comment]
Hm, I don't see much of a point to this. I'm pretty sure he's asking about a particle effect to the armor, but that is what /buytemp is for. Plus, it'll be crazy watching everyone, everyone, running around the server with particles.

**Comment by johnnywoof** [comment]
Closing due to a lack of explanation.

**Comment by 5d100** [comment]
this is pretty much saying add an armor that gives you, say 15 hearts instead of the usual 10.
