### ISSUE TITLE
Degrading Bank Interest

### ISSUE THREAD

**Issue by SonOfDeath** [drewhoener/JWSuggestions#6]
A lot of people are getting TONS of money from the bank..

So money for some people is expendable and will practically never run out. 

Currently the interest is fixed at 1% (I think)

For each 10k that percent should decrease and when it gets to a really high point like 100k there would be no interest. Or whatever system you guys can make up :)

Money should be earned by work (or getting lucky) and working to keep something and to get new things or doing new things is what makes this server fun :)

**Comment by johnnywoof** [comment]
I wish I could reduce it, but then players *cough* @rockerjman222 *cough* would be angry at me.

**Comment by SonOfDeath** [comment]
How about if we keep the current interest rate however whenever they withdraw they lose a % of what they are trying to withdraw.

Ex.
Herobrine wants to take out 1000$ 
But the 2% fee takes 20$ away 
Herobrine only gets 980$ from the bank
(Not that bad)

I only used the 2% as an example.

**Comment by drewhoener** [comment]
Hmm, I'm thinking of Harm right now. She has one of the most frequented shops in the entire server, and works hard to maintain it. She has (in a sense) earned all that money that she has. Another argument is that actual banks don't cut off your interest when you get too rich do they?

**Comment by SonOfDeath** [comment]
Good thought, there are people like Harmony that earn their money by working and not just by stockpiling money. 

!ban RealLife 0 
But seriously, real banks would not have a nice 1% interest rate either ( More like 0.01% or less!)
I like johnny suggestion  "a limitation on how much you can withdraw from the bank every 24 hours."
because most debit cards have this limitation.

No matter what y'all decide people will complain if it hurts them in any way. But I dunno.. This server is very different from others..

**Comment by drewhoener** [comment]
Lol it's true that most banks will NEVER give you a 1% interest rate xD. I also like the idea of nerfing the withdraw amount per day. I think it's a better idea than changing the interest. Might just be me, but I don't think we've ever struggled with our economy to the point where serious action is really necessary

**Comment by SonOfDeath** [comment]
I think changing how much you can withdraw is the best option :P but how much? 5k a day?

**Comment by drewhoener** [comment]
Not sure. I've taken out tons to buy rarer things like beacons all at once so it shouldn't be really small

**Comment by johnnywoof** [comment]
The bank is suppose to be a savings account, it isn't meant to replace your balance.

**Comment by johnnywoof** [comment]
In addition, many players earn 20-30k every day just from the bank alone.

**Comment by SonOfDeath** [comment]
Maybe we should make a max to how much you can get from the bank...

**Comment by sweetharmany** [comment]
+1 on the max amount you can earn in interest rate a day.  Still gives the benefit of putting coins in the bank, without making it so op.  20k+ a day in interest is waayyyy to op.

**Comment by drewhoener** [comment]
And would that be all at once? You still only get interest once per day

**Comment by SonOfDeath** [comment]
What do you mean by that?

**Comment by SarabiMami** [comment]
Just to point it out, IRL, after you reach a certain amount of money in a bank, they will up your interest rate, and if it is a truly significant amount they will up your interest significantly. They do this to encourage the customer to keep depositing and/or keep their amount deposited that high or higher. banks need that money to lend out, grow, stay afloat and rise. So real life and minecraft are very very different. Just saying all this because of what son of death said. However in minecraft as far as i know Johnnywoof doesnt get any bonuses from us users placing money in his bank we do. In the end I agree with a limitation but not a reduction of the interest rate as well. (lol in real life the banks would be fighting over harmony to offer her a higher interest rate to keep her in their bank)

**Comment by SonOfDeath** [comment]
Well this is not real life, if it was there would be other problems. IRL if you put 100,000,000$ yes you would get a bid interest rate but if the bank went out of business you could only get 90,000$ back. Thus making it a very risky investment.

Also the last thing we need is a boost to the interest rank depending on how much money you have in the bank xD

People would be so rich it would make us cry.

**Comment by SarabiMami** [comment]
Omg  I did not ask for an increased interest rate. Could you at least read my last sentence before you assume that. (not the sentence in parentheses ) I said it's not real life, I also said Johnny woof doesn't get any use out of our banked money. As in him even giving us an interest rate all is him being nice.

**Comment by SonOfDeath** [comment]
From what I got from your message you sounded dissapointed that there weren't any bonuses and you spent most of the comment focusing on real life leading the reader confused.

I believe that johnny said earlier that the bank is like a savings account so thats why there is interest :P

**Comment by rockerjman222** [comment]
having interest just as my main source of income on the server, I would have to say that the whole limiting of the how much money you can take out is garbage. you have earned that money it is yours to spend however you wish. I'm not really down for the whole adding a cap to how much you can make from interest either. but what i am defiantly down for would be to downgrade the interest rate to 0.001%, meaning if say you had 200k in the bank you would get 200 a day as opposed to 20k

**Comment by OoveVolcae** [comment]
If you have 200k in the bank you only get 2k a day anyway. If we changed from 1% interest to .001% interest the new players would have absolutely no reason to put anything in the bank, and it would be useless for them. If a player earns 5k and banks it, they get 50 coins a day. Most players aren't rich in the server, it's just the rich players that gain a lot of money each day. I get limiting the money earned with loads of money in there, but we can't neglect the needs and/or benefits of/for new players.
