### ISSUE TITLE
/bank withdraw all  /bank deposit all

### ISSUE THREAD

**Issue by IcyMonkey41** [drewhoener/JWSuggestions#62]
I think it'd be nice if you could do /bank withdraw all  and /bank deposit all.

/bank deposit all would deposit all of your money into the bank

/bank withdraw all would withdraw all your money from the bank

It would be nice to have these two commands added for easier depositing and withdrawing without having to check balances

**Comment by JensieXD** [comment]
Good idea!

**Comment by johnnywoof** [comment]
Deployed.
