### ISSUE TITLE
Demolisher's Wand

### ISSUE THREAD

**Issue by MiniReggie** [drewhoener/JWSuggestions#66]
IGN: LilicaArde

Request: A demolisher's wand as a lord donator perk. 
Details: It would basically have the opposite purpose of the builder's wand where it would remove 9 blocks at a time. To make it fair, no items would be dropped only for pure land removal. I recently saw a post about a flat build world and I think this would be enough to compensate. It would particularly be useful with our ever growing towns in the Johnnywoof survival. A lot of people complain about excavating for builds, towns & what not and this would make everyone's lives easier. It would also make Lord Donator more appealing and more worth it for the $100 donation.  Comments? :)

**Comment by johnnywoof** [comment]
I'm more afraid of the abuse it'll cause. The build wand at least required you to have the blocks at hand, but the demolisher wand would allow blocks to be destroyed forever.

**Comment by drewhoener** [comment]
Yeah, I coded the whole thing yesterday and tried it, it's waaayyy to OP. Unfortunately I think /super will be the best people can get
