### ISSUE TITLE
Baby Disguises

### ISSUE THREAD

**Issue by Lephhyre** [drewhoener/JWSuggestions#67]
Baby Pig, Baby Cow, Baby Villager, Baby Sheep, Dog etc.

**Comment by Lephhyre** [comment]
Also maybe different color variants of sheep?

**Comment by NightHawk164** [comment]
You do realize we can dye ourselves when we're sheep right ahaha.
But baby everything, I'm scared to see the list.

**Comment by PianoPlayingHusky** [comment]
We can dye ourselves?!

**Comment by 5d100** [comment]
we can indeed. it's pretty great, as it messes with people that don't know that disguises exist.

**Comment by johnnywoof** [comment]
Implemented.
