### ISSUE TITLE
Beginners book (JohnnyWoof For Dummies)

### ISSUE THREAD

**Issue by SonOfDeath** [drewhoener/JWSuggestions#7]
I think it would be nice for new players to have a handbook that explains things like: What is a sponge? What is the Mineworld? How do I get money? 

This would be perfect to better explain the unique things on the server :)

The handbook would be a simple written book that the player gets when they spawn for the first time.

**Comment by drewhoener** [comment]
We used to have these books, but we removed them because we have a tutorial for players when they first enter the game. They can also go back and revisit it at any time. Is it really beneficial to add it back in?

**Comment by SonOfDeath** [comment]
I learn something new everyday :P 
If there already was a book system I wouldn't bother re-adding it.

But at the same time a lot of people just skip tutorials, but then what would a book do :P they will probably just ignore that too xD

**Comment by Duraninator205** [comment]
Yeah i don't think we would need to add this.
