### ISSUE TITLE
WP flags

### ISSUE THREAD

**Issue by draelu** [drewhoener/JWSuggestions#70]
i would like to be able to turn on mob griefing on my sponge. Its a part of the game thats missed on ALOT of servers. yes it can be annoying to have to repair creeper and enderman damage but i find it fun to actually maintain my base rather then just build it and expand.

**Comment by drewhoener** [comment]
Noted, I'll consider it for the future

**Comment by johnnywoof** [comment]
This feature cannot be implemented into a sponge flag, due to the way on how the game works.

**Comment by draelu** [comment]
ok is there anyway u can make it so villagers will pick up crops then? i really would like to put in my villager powered food farm
