### ISSUE TITLE
Do Not Disturb

### ISSUE THREAD

**Issue by draelu** [drewhoener/JWSuggestions#71]
A chat option so we can leave chat but still use commands. Some times i want to be able to just focus on what im working on and not have the scrolling text in the corner. The only way I know of is to turn it off in the settings but then i can't teleport/warp where i need to.

**Comment by drewhoener** [comment]
I'm actually in the process of creating a chat channel system where you'll be able to join/leave channels. It should have the functionality that you want

**Comment by drewhoener** [comment]
chat has been implemented, see the manual for instructions
