### ISSUE TITLE
Lord Donors~ Repair

### ISSUE THREAD

**Issue by PanicStingray77** [drewhoener/JWSuggestions#72]
So I was thinking that lord donators would get ONE /repair for an repairable tool (with out sleep, spawner pickup, one-hit, ETC.) Every 4-5 Days. I think this should be added because many lord donators use tools such as swords, and having a /repair with a cool down would help a lot, there is also the fact that we need more perks ;)

**Comment by johnnywoof** [comment]
Any command related to repairing an item will not be implemented.
