### ISSUE TITLE
Lord Donator~ More Perks

### ISSUE THREAD

**Issue by PanicStingray77** [drewhoener/JWSuggestions#73]
So I have a few more Ideas as to perks that Lord Donators Could have, and I'm pretty sure you have heard them many times before in a Skype call, team speak, etc. 
1. Color Customization, The lord donor will be able to change their name from the Aqua blue it is originally set as to a color of their choice, So instead of he blue, maybe someone could have the magenta instead, I think the command should be /name color {Color Code &6,&d etc.} /nd for short, and should have a cool down because people changing the colors every 2 seconds would get REALLY annoying. I think the cool down should be 24 Hours (1 day) So when you choose your color you'd have to choose wisely. 

2. Hammer- I honestly don't know what the item for it would be, but I would break a 3x3 area dropping the items it broke- This would be VERY useful because Clearing land takes forever, but with this it wont.

Remember, These are just Ideas/Things that would be cool for you to add! :smiley:

**Comment by drewhoener** [comment]
Lol are we just adding all the modded items now?

**Comment by johnnywoof** [comment]
The hammer will not be implemented, because of it's extreme nature.
The color customization is a maybe.

**Comment by PanicStingray77** [comment]
:3 LOL So trew red

**Comment by PanicStingray77** [comment]
True**

**Comment by KnittingPaws** [comment]
Some fun stuff for Lord Donators would be to clear grass in a radius of 50 blocks with a command or wand click. Or to locate the nearest water or lava.

**Comment by TemperrroniPizza** [comment]
Knitting, that's what the builder's wand does, its called world edit.

**Comment by drewhoener** [comment]
@TemperrroniPizza uh false. the builder's wand is a modded item.

**Comment by TemperrroniPizza** [comment]
@drewhoener Okay, Thanks for patching up the confusion.

**Comment by johnnywoof** [comment]
Closing due to my final verdict of not implementing any of the suggested ideas.
