### ISSUE TITLE
About Veinminer

### ISSUE THREAD

**Issue by Duran1** [drewhoener/JWSuggestions#75]
How about Veinminer on axes so it automines trees

Benfits:
Less dying during night
Boom in wood prodution

**Comment by drewhoener** [comment]
https://www.youtube.com/watch?v=qQd4ns3-K3A
Imagine having to teach a computer program what a tree is.

**Comment by johnnywoof** [comment]
Due to the complexity of teaching a computer program on how to recognize a tree, this will not be implemented.
