### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by Duran1** [drewhoener/JWSuggestions#77]
I have a few Rank ideas
The first is: Epicdonator should get the builders wand because both lord and Epic would have one wand
The final one is a new staff rank: ChatMod They can mute and kick people for spamming and can't answer modreqs then they will get promoted to helper if there is a spot open

**Comment by BlueKnightSam** [comment]
I can already say the new staff rank is a bad idea and won't happen. Helper really is the chat mod, they have access to mute. Kick is a police ability. So I don't think that will be a rank.
Lord Donators are already cheated of new perks, Epic has a lot already so Lord is the only who will get it as there are not a whole lot of perks for them.

**Comment by drewhoener** [comment]
"The first is: Epicdonator should get the builders wand <b>because both lord and Epic would have one wand</b>...."
There is only one wand...

**Comment by johnnywoof** [comment]
I don't see the benefit in this.

**Comment by Duran1** [comment]
The Lord donator has both the arrow wand and Builders
