### ISSUE TITLE
Prison

### ISSUE THREAD

**Issue by Duraninator205** [drewhoener/JWSuggestions#8]
A prison server with ranks A for 3k b for 6k c for 10k d for 30k and E for 100k and then Free for 150K
That means it a little harder to make money on the Prison server

**Comment by drewhoener** [comment]
Why should this be added? What are benefits? More explanation necessary

**Comment by Duraninator205** [comment]
If it was added it would make the server bigger and have some gamemodes (like surivial) be less lagy

**Comment by SonOfDeath** [comment]
I'm kinda confused of what you're even offering..

**Comment by johnnywoof** [comment]
What are the benefits of adding a prison server?
Why should we add a prison server?
Will players be active on the prison server?

**Comment by SonOfDeath** [comment]
Ok I now see what you mean, but this server is not a prison break server and they're so boring! You just keep doing something over and over again until you get to the next level, if I wanted to farm I would play world of warcraft.

**Comment by Duraninator205** [comment]
I don't know how to explane anymore so you can close if want
