### ISSUE TITLE
Spawnerpick

### ISSUE THREAD

**Issue by Duran1** [drewhoener/JWSuggestions#82]
Spawnerpick  should have at least 10 uses the 4 makes it useless

Benifits:
Less Spam for spawnerpick
Prices for spawnerpick will go up

**Comment by drewhoener** [comment]
False. Economics decreases that the price will go down

**Comment by drewhoener** [comment]
Dictates*

**Comment by BlueKnightSam** [comment]
I see no benefits in this at all. The reason why it is at four is so people don't go spam mining for spawners which they then sell for low prices after a while as it becomes to common in the economy. Also it becomes easier to build mob farms = a lot more money in circulation.
