### ISSUE TITLE
1.9 Ideas

### ISSUE THREAD

**Issue by Duran1** [drewhoener/JWSuggestions#83]
With 1.9 comes a new end biome i think we should make a mineworld verison of the end so we can see the feature when the first 1.9 snapshot comes out

and my other suggestion is could we make the server compatibal with the first snapshot of 1.9 which comes out tomarrow

**Comment by BlueKnightSam** [comment]
We can't add snapshots that easily. As well it has not been discussed to what will happen with 1.9. That has to happen with the staff but for now, this idea I say 90% will not be added.

**Comment by drewhoener** [comment]
I can personally say I won't let the server be upgraded until the API and all tools that make our plugins able to run are updated. So unfortunately, that means no snapshots D:
But yeah, we do plan to do SOMETHING with an end mineworld, no speculation on it though, we'll have to wait for the actual release, things are bound to change slightly

**Comment by johnnywoof** [comment]
1.9 needs to come out first.
