### ISSUE TITLE
Rank stuff

### ISSUE THREAD

**Issue by Duran1** [drewhoener/JWSuggestions#84]
1. I think /feed should be for Ultiment and /heal stays with epic
2. Also i think there should be a rank call youtuber so the server can get bigger via youtube and to get   the youtuber rank you need to be ultiment or higher and be active on the server the youtuber rank gets the same perks as the rank you had before you got the youtuber rank
3. Another disguse should be elder guardian for lord+
4. And epic donator should get 1k doating
5. Pro Donator should also get /fly

And those are my ideas!

**Comment by BlueKnightSam** [comment]
I don't like the Youtuber rank. Always have hated it.

**Comment by drewhoener** [comment]
+1 for everything @BlueKnightSam has said

**Comment by johnnywoof** [comment]
Donator perks will not be changed.
The youtuber rank, I don't necessarily like it that much. Only channels well over 100k subscribers should deserve it, not ones with any lower amount.
The elder disguise has been mentioned here: 
https://github.com/drewhoener/JWSuggestions/issues/57
