### ISSUE TITLE
Keep it survival, don't add any more servers

### ISSUE THREAD

**Issue by FinnB1** [drewhoener/JWSuggestions#86]
Minecraft Username: FinnB
Request: To not make any more servers e.g. adding a creative or minigames or stuff. 
I think you should not do this because no one really wants it and I think it will mean less people joining the server. I've had experience with this as I was moderator on a survival only server which recently added many more servers. It used to get about 20 people at peak times but the addition of these extra servers just meant that no one really played anymore (not sure why but it just wasnt appealing). The consequences meant that now there are only about 7 people on at peak time and I think they may be shutting down soon. Adding maybe 1 or 2 extra servers may work with the current playerbase but I doubt that adding 4 or 5 will be beneficial.

**Comment by johnnywoof** [comment]
Closing since this isn't really a suggestion.
