### ISSUE TITLE
Locking pressure plates

### ISSUE THREAD

**Issue by glitch159** [drewhoener/JWSuggestions#88]
Hello :) when my friends and I play in the survival server, we tend to get people running through our little settlement. they tend to stop by our homes, and get through locked doors using pressure plates. I would like it if one could /lock a pressure plate from anyone but yourself being able to use it. thanks :)

**Comment by drewhoener** [comment]
If you have a protection sponge, just make sure pressure plates are disabled with /wp flags

**Comment by glitch159** [comment]
a... protection sponge? Well, idk what that is, but ty

**Comment by BlueKnightSam** [comment]
/warp sponge tutorial will give you more info on sponges but they protect land.
