### ISSUE TITLE
Voting Crate System!

### ISSUE THREAD

**Issue by TemperrroniPizza** [drewhoener/JWSuggestions#90]
Voting for 225 coins is great and all, but adding a voting crate would be awesome because it would entice players to vote more because they could earn gear and items that are very useful to them. BUT... you'll only get one key for every 3 votes.

**Comment by TemperrroniPizza** [comment]
If you craft 9 vote keys together, you get a legendary key that can get you armour, tools and weapons, special perks, donator abilities, morphs, and/or more expensive items like beacons, and diamonds. It would be fantastic for your server, because it adds more of a challenge as it will not only get them something great but will help the server substantially.

**Comment by TemperrroniPizza** [comment]
It's highly recommended that this is added.

**Comment by drewhoener** [comment]
So, the thing about this is first of all, it completely undermines our donor track ranks. second of all, it's not really survival if everyone gets all the stuff that takes a lot of effort to get through a simple chest. And last of all, the coins gotten through voting can be used to either buy outright, or buy the crafting components of the items you're describing

**Comment by drewhoener** [comment]
Also, who "strongly recommends" it
