### ISSUE TITLE
Town shop signs

### ISSUE THREAD

**Issue by JensieXD** [drewhoener/JWSuggestions#92]
Could it be possible to add shop signs for towns, so the money goes directly to the town bank?
Thanks

**Comment by JensieXD** [comment]
Any more information about this idea?

**Comment by drewhoener** [comment]
I've thought about it for a while, and given that I'd have to add several other data types to towns just to even consider changing the system, it would be a bunch of work. Also, towns aren't player instances so they wouldn't natively work with the econ system and it'd have to be tooled around them. Just becuase of how much I'd have to alter the existing system to make it fit in, I don't think it's a possibility anymore, sorry
