### ISSUE TITLE
Tameable mobs

### ISSUE THREAD

**Issue by Duran1** [drewhoener/JWSuggestions#93]
I think with a spiecal diamond (Crafted with a diamond next to an emerald) You can tame 1 hostile mob 
for an unlimited ammount of time  and it fights with as if a wolf would or this could be a token feature for 15 tokens

**Comment by drewhoener** [comment]
I can consider it, but I'm not sure everyone realizes how much work went into the one custom mob that's already in buytemp. Almost all the AI had to be redone. I'll keep this in mind but it is a big undertaking

**Comment by johnnywoof** [comment]
Maybe, I do like the idea and was considering it.

**Comment by johnnywoof** [comment]
Due to the extreme effort required to code this in, this idea will be dismissed for now. Maybe it can be possible in the future.
