### ISSUE TITLE
Extra custom enchants

### ISSUE THREAD

**Issue by Duran1** [drewhoener/JWSuggestions#94]
There should be such thing of unlucky encahnts such as:
Looks-good: Everytime a mob is killed you get hunger IIII for 5 seconds 1/5 chance
My-friends!: Summons 5 more of the mob you killed 1/20 chance
Haunted: Everytime you killed a mob with this weapon you get Posion V for 5 seconds 1/35 chance
Breaking: Makes the tool/Weapon/armor break easily with a range from Breaking I - Breaking III 1/25 for L 1 1/30 for L 2 and 1/35 chance for L 3
Bees: When a log is broken you lose 2 hearts when a leave is broken you lose 1 heart 1/50
Ouch: Extra damage on armor (if on armor) 5 hearts of damage when your tool breaks 10 hearts of damage when a weapon breaks (if on tools or weapons) 1/30 chance on all
Cheap: No coins for when a mob is killed 1/60 chance

**Comment by johnnywoof** [comment]
Enchantments are designed to improve the item, not to degrade it.
