### ISSUE TITLE
Increase the server render distance

### ISSUE THREAD

**Issue by TemperrroniPizza** [drewhoener/JWSuggestions#97]
Hey there, I noticed that after rendering more than 8 chunks, it wouldn't go any further. Although it would be nice to render out all 32 chunks, 20-25 chunk render distance would be fantastic for running shaders and a 512 pack. I can finally benchmark a good PvP ready PC.

**Comment by TemperrroniPizza** [comment]
IGN: _Mumbo

**Comment by johnnywoof** [comment]
More chunks, more lag.
