### ISSUE TITLE
/xptop

### ISSUE THREAD

**Issue by TemperrroniPizza** [drewhoener/JWSuggestions#98]
IGN: _Mumbo
Request: As the person with the most xp levels on the server at 210, it would be nice to have a command that shows the top 10 players' xp levels.

**Comment by johnnywoof** [comment]
This is possible for online players, but for offline players most likely not.

**Comment by TemperrroniPizza** [comment]
That's why there should be a capturing system, the console would see what xp level a player is at when going offline.

**Comment by drewhoener** [comment]
But why would we cache something like that? I for one can't see the rationale for it, other than bragging rights, which I assume this is about

**Comment by Duranduran05orDuran** [comment]
That's a cool idea

(I have 442 XP)
